### ISSUE TITLE
Need synchronization of text files for further translation in the Crowdin service

### ISSUE THREAD

**Issue by click0** [Valansch/RedMew#1021]
Subj.

For there are no such lines:
https://github.com/Refactorio/RedMew/blob/e0dadb7de5adb2c0575e2703f3775989301e013a/locale/en/redmew_features.cfg#L166

**Comment by SimonFlapse** [comment]
I've updated the crowdin files to match https://github.com/Refactorio/RedMew/commit/d45009d1aabf787bbc8f7f11ecaf734dad168af5

However it only resulted in one new string added in the Features file.

Thanks for your interest in our localization
