### ISSUE TITLE
Jailing players while they're in a spidertron causes issues

### ISSUE THREAD

**Issue by Jayefuu** [Valansch/RedMew#1102]
I don't have any more details for now. Reported by Tigress88 on Crash Site. Leaving this not here for me to look into it.

**Comment by Ferefang** [comment]
cript @/external/factorio/7/temp/currently-playing/utils/command.lua:261: Error while running 'jail' with arguments {player = "MeggalBozale"}: Entity is not car or unit or projectile or artillery-projectile

**Comment by Jayefuu** [comment]
Thanks @Ferefang, I think I can fix this so will have a go.

**Comment by Jayefuu** [comment]
This is now fixed and merged.
