### ISSUE TITLE
Timer on /report does not work

### ISSUE THREAD

**Issue by MommyTigress** [Valansch/RedMew#1107]
When a player uses the report feature to report another player, the pop up when an admin logs into the game is supposed 
display the game time that report was received and how long ago that was. It does not display how long ago it was received properly. It always states 0 seconds ago.

The report feature should state game time that report occurred AND how long ago that was.

1. Player uses /report while no admin is online
2. Admin logs into map and report pops up.

![timer](https://user-images.githubusercontent.com/74326785/98991706-384e1f80-24fa-11eb-8a74-231014580dff.PNG)

I had a player create a /report before I logged in. In screenshot you can see the timer that says 0 seconds ago. And in the chat, you can see the game time showing that it was actually reported 11 minutes ago.

**Comment by grilledham** [comment]
Took a quick look through the code. My guess is the reports are shown for the admin player even when they are offline, so when the admin rejoins they see the report that was opned the moment the report was raised. In other words the minutes ago doesn't update when the dialog is open, or when the admin joins again.

So we either update the time when the admin player joins, delay showing the report dialog until the admin player joins, or update the time every minute with a timer.
