### ISSUE TITLE
Banning offline player clashes with inventory dump on crash site

### ISSUE THREAD

**Issue by Jayefuu** [Valansch/RedMew#1282]
@grilledham no further investigation than this image. I banned someone from the web interface while they were offline on crash site.

![image](https://user-images.githubusercontent.com/28716932/150307807-a54c12d3-9504-4e57-9be3-086a4f5c4ef8.png)

**Comment by grilledham** [comment]
Tried to reproduce it and couldn't. But clearly `get_inventory`  is returning `nil` so I will add a nil check.
