### ISSUE TITLE
Update fish dialog box with... something?

### ISSUE THREAD

**Issue by TWLTriston** [Valansch/RedMew#131]

**Comment by Valansch** [comment]
Whats going on here?

**Comment by TWLTriston** [comment]
Current text should change from what's below to something else:

> 
> Hi stranger, I'm a fish..
> And this is what you ought to know:
> 
> - Please be nice and don't grief. Or else.. ;)
> - Admins: Don't abuse. Don't fight other Admins.
> - Don't argue with other players for silly things.
> - No political, racist, or misogynistic content.
> - If you suspect you desync, restart the game.
> - Join our growing community on discord.me/redmew
> - Post server pics (or didn't happen): redmew.reddit.com
> - Contribute to our Hookers & Blow Fund with:
>   Bitcoin: 18PferSFbkwsYai8sLnWKzrr8YXQ1bBqNg
>   Paypal: paypal.me/jsuesse
>

**Comment by Valansch** [comment]
What do you suggest?

**Comment by Valansch** [comment]
yes scrap the subreddit and change discord. But why remove the links? O.o
