### ISSUE TITLE
Donator perk "train saviour" doesn't work with modded trains

### ISSUE THREAD

**Issue by JamesFWilliamson** [Valansch/RedMew#1421]
The donator train savior perk works by checking death cause against a list of item names, as shown here:
https://github.com/Refactorio/RedMew/blob/a1f1b81ca422b04212d98cfddbd12f56a20346e6/features/train_saviour.lua#L28

However if the train or carriage is modded then it's not in that list of names and so the player doesn't get saved. I know this is an edge cases for modded only games but would it be reasonable to change the behaviour of train saviour so that instead of checking against a list of names in entity-name it checks against the item-subgroup to see if it's in train-transport?

**Comment by RedRafe** [comment]
Maybe check type directly. So it would work for any vanilla/modded entity, regardless of name/item subgroup which are inconsistent with modded entities
