### ISSUE TITLE
Change folder structure

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#152]
move 
- [x] _locale back to locale (first)
- [x] move all files in locale into appropriate folders.
- [x] change all include statement to reflect the new paths.
- [x] remove unused files
- [x] cleanup map_layout #115

**Comment by Valansch** [comment]
My suggestion:
- locale/gen_*subfolder*/ ==> gen/*subfolder*/
- locale/utils/ ==> utils/
- locale/resources/ ==> resources/
- /locale/gen_combined/grilledham_map_gen/data/ ==> data/map_gen/
  or maybe resources/map_gen/ or resources/data/map_gen/?

@grilledham @TWLTriston whats your take?

**Comment by grilledham** [comment]
This makes me think there is a lot of clean up / updating work I need to do for my maps.
I should update the maps based on an image to use 0.16 tiles and use the compressed format. The problem is I don't know if I still have the source image for all of them.
Also I should remove old / test maps.

**Comment by Valansch** [comment]
Okay but we should probably do that in a seperate issue and PR. This one is pretty big by itself already.

**Comment by Kovus** [comment]
Btw, you don't need to abuse the locale folder anymore.  From the 0.16.0 patch notes https://forums.factorio.com/viewtopic.php?f=3&t=54538 :

```
Scenarios can contain folders with arbitrary names.
```

**Comment by Valansch** [comment]
I know, thats why we are restructure :)
