### ISSUE TITLE
Update grilledham maps

### ISSUE THREAD

**Issue by grilledham** [Valansch/RedMew#153]
- [x] Update maps based on an image to use 0.16 tile names and the compressed format.
- [x] Remove old / test maps.

Waiting for #152.

I did also think about adding a source image sub folder to the repo, in case tile names change again.

#156 - Completes this issue

**Comment by Valansch** [comment]
Source image folder is good. Maybe /data/source_images or something?

**Comment by grilledham** [comment]
I was thinking there would be:
grilledham_map_gen/presets
grilledham_map_gen/data
grilledham_map_gen/source_images
And have the filenames the same in each sub folder.

**Comment by Valansch** [comment]
Do you insist on your name on the path? I think it makes more sense to leave it out.

**Comment by grilledham** [comment]
No, you can take my name out. I only did it originally to keep my files separate.

**Comment by Valansch** [comment]
Okay then. How about:
- map_gen/presets
- map_gen/ores etc
- data/map_data/
- resources/source_images/
- resources/map_preview

**Comment by grilledham** [comment]
what about map_gen/data instead of data/map_gen, or do you prefer data/map_gen.

**Comment by grilledham** [comment]
where are you planning to put :
grilledham_map_gen/builders.lua
grilledham_map_gen/map_gen.lua
grilledham_map_gen/map_gen_not_threaded.lua
in map_gen/presets?

**Comment by Valansch** [comment]
i would put that in map_gen/
So we have 
map_gen/builders.lua (plus the other 2)
map_gen/data/
map_gen/presets/
map_gen/combined/
map_gen/ore/... etc

Do you find putting it there unsuitable?

**Comment by grilledham** [comment]
I am okay with your proposal.

**Comment by Valansch** [comment]
i will rename map_gen.lua into generate.lua, since the folder is already called map_gen.

**Comment by Valansch** [comment]
After fiddeling with alot of that stuff i changed my mind. Maybe its not a bad idea to have your stuff seperate. Right now it is kinda everywhere. What do you think about having anything used by your scripts inside map_gen/grilledham_gen/?

**Comment by grilledham** [comment]
That's fine, I'm pretty easy with whatever you decide is best. 

I guess this could be considered a separate proposal, but I'm wondering if the map_layout logic could be simplified. 
As I see it there are 3 different modules:
- modules that do just tiles (currently everything in gen_shape + some of gen_misc + some of gen_terrain + some of gen_combined (including grilledham_map_gen))
- modules that do just entities (currently some of gen_misc + gen_ores + some of gen_terrain)
- modules that do both (currently most of gen_combined (including grilledham_map_gen))

Maybe in map_layout there could just be a modules = {} global list and each map script just adds itself to the list when it's required. Then the on_chunk_generated function just loops through the modules.

We would still organise the modules in folders based on their type, maybe with different folder names, maybe with the same. Also some very specialist modules that don't change tiles or entities like rusky_pvp wouldn't need to be added to the list when required.

Anyway I'm just thinking out loud, let me know what you think.

**Comment by Valansch** [comment]
Yes i agree that is could be simplified. I already have an issue open for that. The idea that running one module type before the other proved ineffective at best. We added more and more edge cases and its just a mess. All modules should be able to run with any other module. This doesnt mean they are compatible, but thats not guaranteed right now anyways.

**Comment by grilledham** [comment]
yeah, it's up to the mapmaker / person setting up the config to know what can go together and what can't. It should be obvious anyway.

**Comment by grilledham** [comment]
#156 - Completes this issue
