### ISSUE TITLE
Make scenario stats output

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#159]
We want to extent the discord bot to support things like /playercount.

To do this we have two options:
- Only change the bot, use lua commands to output into the log files and parse the log files.
OR
- Make the bot call a lua function, that outputs json into a file, which the bot can read and interprete

In my opinion the 2nd option is easier and cleaner, hench the issue.

I will take care of the bot code in the server backend.
What needs to be done in the scenario is:

 - [x] Create new file (something like server_api.lua)
 - [x] Include the file in control.lua
 - [x] Implement non-local functions in that file that can be called from the server console and output into a file in the script output folder (something like api_output.txt)

**Comment by Valansch** [comment]
Toledin wanted to take this issue, so i will be here to help.

**Comment by ZTByte** [comment]
Done.

**Comment by ZTByte** [comment]
test

**Comment by Toledin** [comment]
you can close this issue
