### ISSUE TITLE
Implement /moonwalk

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#199]
Makes the player walk backwards.

**Comment by theorangeangle** [comment]
I love this - 
maybe we should also consider changing the "death from excessive market speed upgrade" into a 50/50 chance of death or moonwalk :D

**Comment by Valansch** [comment]
Closing because character.character_running_speed_modifier must be greater than -1.
It would require its own force and that would introduce so many work, edge cases and problems with other code that it won't be worth it.
