### ISSUE TITLE
Implement adminchat

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#200]
We may need to find a better name, but the idea is pretty simple.
/a Hello World
results in:
(Admin) Valansch [HR Department]: Hello World

**Comment by grilledham** [comment]
what do you think about a regular chat, that goes to all regulars + admins?
For example if there is a griefer and a regulars wants to let admins / regulars know about it.
We can't use /r though 🤔

**Comment by Valansch** [comment]
Instead we should have a /report feature i think.

**Comment by grilledham** [comment]
We should add a /report
I kind of like the idea of regulars talking to each other and helping find griefers, but it's not a great solution, you need admins ultimately. 
It was just a passing thought anyway

**Comment by Valansch** [comment]
That would be neat but its not gonna happend and yes you are right it wont do much if no admin is around. What i usually see it people yelling griefer and then the griefer is alerted. So we should have the regulars know that there is a report they can use.
Right now when someone does that i tell them to whisper an admin next time.

**Comment by plague006** [comment]
Closed by https://github.com/Valansch/RedMew/commit/a9a755826faeb7dd26be2715a5905f9a26043948?

**Comment by Valansch** [comment]
Yes
