### ISSUE TITLE
Remove spyshot

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#201]
Lacking volunteers to run the upload script we may as well remove this features.

**Comment by plague006** [comment]
I think if people were explained what it did and what was required, people would be willing to do it.

**Comment by theorangeangle** [comment]
Yeah, maybe keep it for now and see if 0.17 opens up any easier ways to accomplish it

**Comment by grilledham** [comment]
The ultimate solution to this would be to periodically open the autosaves on a second headless server, have it output the map to a custom format, then process that using a custom renderer (like the blueprint to img converters that are popular on discord and reddit).

But that's a rather large project and not something I fancy working on currently.

I think it's unlikely 0.17 will make any changes in this area.

**Comment by Valansch** [comment]
0.17 will not help us. The headless server doesn't have sprites by design and it will never and should not have sprites.

@grilledham what you are describing is something different from what the spy command was tho. You are describing snapshots of the map. Which would be cool. But i want to see air20 nuked when i do /spy air20 :D

**Comment by Valansch** [comment]
ef11d6f closes this
