### ISSUE TITLE
Have a jail and/or ban button on the report popup

### ISSUE THREAD

**Issue by plague006** [Valansch/RedMew#215]
Would be handy to have a button on the report popup to quickly pop someone into jail while investigating. Mockup image to show exactly what I mean.
![jail button mockup](https://user-images.githubusercontent.com/10162554/44679354-bea8e480-aa08-11e8-8773-8bffa114a88d.png)

**Comment by iltar** [comment]
Yes please! 

Another feature I's love to see, is a "view player" button, where it will move your viewport to see what the player is doing. What I'm also missing is a way of seeing this window when you accidentally close it, like pressing ESC at the same time as it opens.

**Comment by plague006** [comment]
@iltar You can also use /find-player <name> to get an alert, I find that generally adequate to find offending players.
