### ISSUE TITLE
"Missing event argument" on custom scenario generation.

### ISSUE THREAD

**Issue by Jemjem787** [Valansch/RedMew#23]
EDIT: It seems the issue was the version of factorio. This was made for the .15 beta, not the current stable .14 release. 

When i try to generate the scenario i get this error.

...Data/Roaming/Factorio/temp/currently-playing/control.lua:7:
...Data/Roaming/Factorio/temp/currently-playing/chatlog.lua:87: missing event argument

[Screenshot](https://i.gyazo.com/ba152e58019cb571c1d8af98ae0a975f.png)

What i then tried to do was edit out line 7 in control.lua (require "chatlog"). That led me to similar errors to (--require "band") (--require "fish_market") (--require "custom_commands") (--require "nuke_control"). Once i edited out all of those lines, i got a error "Unknown item "programmable-speaker". I have hit a wall with this.

Windows 7 64bit
Steam Client
Have confirmed i have the latest updates to factorio and windows.

**Comment by Valansch** [comment]
Thanks for the report.
I will have a look into this if i have time. 
But it might take a while. We are developing for 0.15 so this does not have a big priority for me right now.
I guess the only fix for now it to use 0.15. Sorry about that.

**Comment by Valansch** [comment]
15.31 is now stable. And this isn't an issue on stable, this will probably not be fixed.
