### ISSUE TITLE
Implementation of Messaging System "You Got Mail"

### ISSUE THREAD

**Issue by gentlecastaway** [Valansch/RedMew#26]
https://mods.factorio.com/mods/Gangsir/YouGotMail

I will talk anyway with its creator to see if he can give us a hand ;)

**Comment by Valansch** [comment]
Probably not gonna need his hand. His permission would be nice tho :D

**Comment by plague006** [comment]
This would be nice if someone opened a PR, but I think it's beyond the scope of the redmew scenarios to write this/keep this issue open. Between the discord to use to send PMs and the fact that maps only last a few days the use-cases don't really seem to exist.

**Comment by Valansch** [comment]
I liked the idea just because its fun. Not all users have discord. But i totally agree the usefulness is limited.
