### ISSUE TITLE
Placing landfill should put in dirt, not grass

### ISSUE THREAD

**Issue by iltar** [Valansch/RedMew#276]
This feature existed, but was removed as landfill was disabled. Should be brought back now that landfill is in the market.

**Comment by grilledham** [comment]
I don't know how you were doing it before, but we have a misc map module for that.
```lua
require ('map_gen.misc.change_landfill_tile')('dirt-1')
```
Should do the trick

**Comment by iltar** [comment]
Would it work with random dirt? I had `dirt-<1,7>` pretty much. If that script does the trick, I'll also take it though. more shared code is better 😄
