### ISSUE TITLE
Show a message when placing solar panels in Diggy

### ISSUE THREAD

**Issue by iltar** [Valansch/RedMew#284]
As solar panels make no sense, why not show a message the first time? Could also prevent placing them, but that would simply raise questions all the time.

**Comment by SimonFlapse** [comment]
What about portable solar panels? They are and, should be, useless too.
Seems the easiest for those is to disable the technology.

**Comment by iltar** [comment]
Sadly not possible
![image](https://user-images.githubusercontent.com/1754678/48313119-30301200-e5b8-11e8-97c3-2c084d67bd51.png)

**Comment by SimonFlapse** [comment]
Oh yeah, missed that one hard. Anyways to disable the recipe? Seems we are not allowed to set hidden on recipies
