### ISSUE TITLE
Redraw the stone sent to surface popup when the amount changes

### ISSUE THREAD

**Issue by iltar** [Valansch/RedMew#285]
Currently the popup is static, meaning it renders once and does nothing after. It should probably be rendered again once stone is sent to the surface. The means you can actively watch it progress. One minor addition, would it make sense to move it to the left top and not block the player window? that means you can have it open while donating to the market and see it progress at that point without having to put it into chests.

**Comment by SimonFlapse** [comment]
I could move it to the top left while doing #300 currently the table has lost a column so it's very wide. Only problem with shrinking is the scroll pane needs to be large enough to not become annoying, and the progress bar would shrink too.

I'll try to do the redrawing too but can't promise it.

**Comment by SimonFlapse** [comment]
Can't open the Market interface while the stone sent to surface popup is open. I don't know what needs to be done so you can? (The player list can be opened while the market interface is open)

**Comment by iltar** [comment]
This done here: https://github.com/Valansch/RedMew/blob/d4324c857edc07923f37ef7fb4123b95efbeafdd/map_gen/Diggy/Feature/MarketExchange.lua#L462

This is like a window focus, where ESC can close it. In theory you can remove this line and move it to the top left without problems

**Comment by SimonFlapse** [comment]
Alright, thanks! That did it :)
