### ISSUE TITLE
Implement ships

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#30]

**Comment by Valansch** [comment]
Spawn ships with /ship nearby.
Ship is made with floor tiles (maybe desert) and walls.
A player can board a ship with something like /ship enter
A player can leave a ship with /ship leave
Every player in a ship can control it.
The players in a ship can not move (movement_state.state = false)
Controls: Accelerate and Rudder.
The ship has an internal speed and Rudder position. 
The ship moves by:
1. Calculating the next position it will be.
2. Check if all effected tiles are either water or ship tiles
 2.1 if not, then the ship just hit land and breaks down
3. Place the center tile of the ship.
4. Tp all crew members to new center tile. 
5. Replace all ship tiles with water.
6. Place new ship tiles.

**Comment by Valansch** [comment]
Wait for #31

**Comment by theorangeangle** [comment]
31 has been closed, is this still considered something you would like to accomplish @valansch? Could be interesting for our water-heavy maps

**Comment by Valansch** [comment]
It can totally be done. I just never have been around implementing it for MP. It was already working in singleplayer. I just didnt have the heart to close this issue, because boats are soo cool. It will also be obsolete with 0.17, since we can use entities in 0.17 :/

Bye ships.
