### ISSUE TITLE
Diggy stone reward system overhaul

### ISSUE THREAD

**Issue by iltar** [Valansch/RedMew#300]
Currently it's a big list of "at X stone, you get reward Y". This is a lot of effort to maintain and balance. It would be easier to have an "at level X, you get reward Y", where the level requirements in stone are automatically calculated. This makes it possible to have infinite rewards, but also allows to make the scaling easier for single player/lan matches.

**Comment by SimonFlapse** [comment]
How do we want the scaling to be calculated? By online players? By number of unique players? Game time? or do we need to set it manually?

**Comment by iltar** [comment]
I think configuration is the best option, because if you it all automated and everyone leaves, it will suddenly fill up really fast. Only thing though might cause issues, is one of the progressbars in the UI. I believe @der-dave already implemented a "level" concept in there, so it shouldn't be too hard to rewrite. Might have to remove the "overall" progress though, as there's no overall progress anymore with an infinite amount of levels

**Comment by SimonFlapse** [comment]
What about the `local function redraw_table(data)` I'm pretty sure it won't like me giving it infinite rows

**Comment by iltar** [comment]
If that works, I won't complain

**Comment by SimonFlapse** [comment]
I think i'm only going to show the market unlockables in the GUI, and make the other buffs the same for each level. We are not really setting the value of the buffs, except in the beginning. If you still wish to have an adjustable value for the buffs per level let me know, and i'll see if i can figure that one out.

**Comment by SimonFlapse** [comment]
From discord: (Edited)
> Would be nice to show the currently active sum of buffs. Could just be the current value from the force

> If you wish to add a price reduction on some things (might be nice for like landfil), it will require re-adding the item. So you'd have to clear + re-add everything. That's a lot easier imo, but you'll have to figure out what to do with the chat messages

> Perhaps we can flash the market button instead and highlight what's new + scroll to it?

> Perhaps invert the sequence of the market items and show the newest on top? Then we could just make a colored line and say, everything above this is new (like discord's unread line)
