### ISSUE TITLE
Diggy biters not spawning due to size

### ISSUE THREAD

**Issue by iltar** [Valansch/RedMew#302]
When digging, it often happens that beyond small biters, they refuse to spawn, this due to biter size and the game not force spawning anything. This kind of breaks the difficulty later on, meaning you can dig really far without any resistance at all. 

What about making biters "destroy" the rocks they would spawn on to force space? This would mean that if no spawn point can be found, the size of a small-biter should be located and a decent sized area auto-mined or destroyed (with special effects?), to ensure biters can spawn.

**Comment by Valansch** [comment]
We don't need to destroy the rocks. The biters destroy the rocks if they are stuck inside a rock. We can just spawn biters without checking for collision :)

**Comment by iltar** [comment]
The problem is that it triggers on void removed, so it will always have a position next to the void, meaning it won't fit anything big. If I get your suggestion correctly, you want to just always spawn it?
```diff
    for _, entity in pairs(units) do
        local position = find_non_colliding_position(entity.name, entity.position, non_colliding_distance, 1)

        if (nil ~= position) then
            entity.position = position
            create_entity(entity)
+        else if (nil == create_entity(entity)) then
            Debug.print_position(entity.position, "Failed to spawn '" .. entity.name .. "'")
        end
    end
```

**Comment by grilledham** [comment]
Shouldn't `find_non_colliding_position` keep searching until it finds a valid position? What is `non_colliding_distance` set to?

**Comment by iltar** [comment]
It's set to 3 in this context

**Comment by Valansch** [comment]
There is no such thing as wont fit. You can just create one entity on top of the other. Even if the biter is stuck in void it will be able to attack the rock and thus create non void and be able to free itself. So yea i suggestion just doing:


```
 for _, entity in pairs(units) do
        local position = entity.position

        if position then
            entity.position = position
            create_entity(entity)

         else if not create_entity(entity) then
            Debug.print_position(entity.position, "Failed to spawn '" .. entity.name .. "'")
        end
    end
```
