### ISSUE TITLE
Split starting items out of control.lua

### ISSUE THREAD

**Issue by plague006** [Valansch/RedMew#305]
Preferably into config.lua since it's a config option.

**Comment by iltar** [comment]
Should it be though? It's really scenario specific, with just a generic sane default for 99% of the scenarios

**Comment by plague006** [comment]
It's absolutely scenario-specific. Correct me if I'm wrong, but could we move the default loadout (currently in control.lua) into the config and have specific maps overwrite the starting items as needed?

**Comment by plague006** [comment]
Closed by #333
