### ISSUE TITLE
Change Diggy resources to weights instead of percentages

### ISSUE THREAD

**Issue by iltar** [Valansch/RedMew#309]
Feedback from Rdjrjqouqcu
> I'd change the 'resource_chances' field in the config.lua to be a 'resource_weights' field instead. This will make adding modded ores easier without having to recalculate the new weights for every other entry. Something like resource_chances['coal'] = resource_weights['coal'] / sum(resource_weights)

**Comment by Rdjrjqouqcu** [comment]
done, will create a pull request once I figure out how to
