### ISSUE TITLE
Corrupt values when removing/placing tiles

### ISSUE THREAD

**Issue by iltar** [Valansch/RedMew#310]
There have been several reports about corrupt values regarding floor tiles. Namely:
 - hazard (refined) concrete not carrying what it should
 - Sometimes a cave-in happens where it shouldn't
 - Adding/removing tiles seems to directly corrupt the stress levels in some scenarios, see gif

https://i.gyazo.com/de38739b0590ac64ef9cded09e6559dc.mp4

**Comment by KufrA** [comment]
@iltar Thanks, then we just have to live with it for this save. Some dedication into each factorio map. Thanks for awesome scenario!
