### ISSUE TITLE
Take screenshot every 2 minutes

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#32]

**Comment by TWLTriston** [comment]
Not sure this can be done, unless the server is running a GUI. As a headless server there is no graphical anything to take a screenshot of.

See: https://forums.factorio.com/viewtopic.php?f=7&t=29296

**Comment by Valansch** [comment]
Dont trust the forum.
http://lua-api.factorio.com/latest/LuaGameScript.html#LuaGameScript.take_screenshot

**Comment by Valansch** [comment]
The post is one year old. But i see what you mean. Maybe we can try it out and close this issue if its not possible.

**Comment by TWLTriston** [comment]
Note: If Factorio is running headless, this function will do nothing.

**Comment by Valansch** [comment]
Lol nvm then. We would need a non headless bot or something.

**Comment by Valansch** [comment]
Reopen because we found a workaround:
Some admins take screenshots and push them to discord via webhook

**Comment by Valansch** [comment]
Closing because the workaround doesnt work in practice. Nobody wants to run the script.
