### ISSUE TITLE
Split the report function out of custom_commands.lua

### ISSUE THREAD

**Issue by plague006** [Valansch/RedMew#334]
We have an entire [report.lua](https://github.com/Valansch/RedMew/blob/develop/features/report.lua). We should probably be calling that instead of custom_commands having its own [report function](https://github.com/Valansch/RedMew/blob/a366d3aaf96b5ef40f7e8581dc6eb16cbfeb38a9/features/custom_commands.lua#L655)

@SimonFlapse would you be willing to tackle this?

**Comment by SimonFlapse** [comment]
It's already calling report.lua but I see where you are going with it. I can take a look at splitting it.

I like the splitting things up, it makes it much easier for me to understand everything.
Everyring just needs some luadoc (or good documentation) and it should start being a breeze to start contributing to the codebase
