### ISSUE TITLE
Clarify the usage of small plane from the Market

### ISSUE THREAD

**Issue by SimonFlapse** [Valansch/RedMew#351]
> we really need to get some description on what the small plan on the market does
_Newcott at 2018-11-15 8:29 PM GMT on discord_

**Comment by SimonFlapse** [comment]
We could remove the small plane and add a 'nothing' modifier which enables the effect_description. This way we could just write train immunity or something like that.

**Comment by plague006** [comment]
Train_saviour was the first thing I wrote for redmew. It can 100% be improved and looking back on it now it makes me chuckle. While we can remove the item requirement, I would propose changing button to a custom button that includes instructions and inserts the item on press. The presence of the plane in a player's inventory is a quick way for them to check if they're train immune without adding more UI or requiring them to check via a command.

**Comment by SimonFlapse** [comment]
So you're alright with it not being an item, but insert the plane as an item to give the immunity?

**Comment by plague006** [comment]
I prefer it being an item, but I wouldn't fight to have it remain as an item.

I think your idea of redoing the button is a really good idea. We can retain all the functionality while just inserting a description.

**Comment by SimonFlapse** [comment]
I'll make the changes tomorrow and we can see if it's something we still like. I'd wish we could provide an description but that'll take rewriting the market interface

**Comment by SimonFlapse** [comment]
![image](https://user-images.githubusercontent.com/44922798/48619295-4e24ba80-e99c-11e8-8799-e043794443f4.png)

I think this is the best I can do. I'd really like to use a different font for the description, but I haven't been able to do that.

**Comment by SimonFlapse** [comment]
While I'm at it, we could clarify the temporary boosts too:
![image](https://user-images.githubusercontent.com/44922798/48620436-72829600-e9a0-11e8-92c3-8c67b034b707.png)

![image](https://user-images.githubusercontent.com/44922798/48620452-7ca49480-e9a0-11e8-8b3a-00884491d5cc.png)

**Comment by iltar** [comment]
Aren't the temporary boosts going to kill you if you spam it?

**Comment by SimonFlapse** [comment]
They are right now, you can remove that, but that'll allow you to get infinite speed

**Comment by plague006** [comment]
In terms of the language:
```
Train Immunity (+1 train_saviour_token)
Each train_saviour_token in your inventory will save you
from being killed by a train once
```

In terms of implementation: you're going to run into difficulties because the way the stat bonuses work is by matching their fixed position in `market_items.lua`. As is, the plane is loaded after all other items and the number of items varies.

**Comment by plague006** [comment]
And in terms of language for the bonuses:
>Increases _ by one for a...

You should specify "one level" or whatever measure you want to use.

**Comment by SimonFlapse** [comment]
Well it's increased by literally 1 not sure how to rephrase that

**Comment by SimonFlapse** [comment]
For it to work i'd have to move the train savior item up onto index 3

**Comment by plague006** [comment]
> 
> 
> Well it's increased by literally 1 not sure how to rephrase that

It's `character_mining_speed_modifier` you're increasing `character_mining_speed_modifier` by 1, but that doesn't mean anything to an end-user, so we have 2 ways to obfuscate that. We can call them levels or we can not specify an amount at all.

`increases speed by one level for a short...`
`increase speed for a short...`

They're both equally as descriptive, but one requires less words :)

**Comment by plague006** [comment]
#356 should help this issue
