### ISSUE TITLE
Diggy join error (2018-11-17)

### ISSUE THREAD

**Issue by SimonFlapse** [Valansch/RedMew#382]
![image](https://user-images.githubusercontent.com/44922798/48666145-2a589600-eabc-11e8-86c6-1b1556d0c908.png)

```
23225.012 Checksum for script D:/FAST GAMES/Factorio_0.15.0/temp/currently-playing/control.lua: 1093740540
23226.114 Error ClientMultiplayerManager.cpp:95: MultiplayerManager failed: "" + multiplayer.script-mismatch + "
" + "
level"
23226.114 Info ClientMultiplayerManager.cpp:573: MapTick(1484782) changing state from(ConnectedLoadingMap) to(Failed)
```

We had the above error happen to minimum 3 players around 21:50 GMT.

**Comment by SimonFlapse** [comment]
[factorio-current-2018-11-17-21_53_07.zip](https://github.com/Valansch/RedMew/files/2592294/factorio-current-2018-11-17-21_53_07.zip)

**Comment by Valansch** [comment]
This is not a scenario issue.

**Comment by SimonFlapse** [comment]
Nothing we can do about it?
I'll leave it for reference if it happens in the future.

**Comment by plague006** [comment]
Closed issues are still included in searches.
