### ISSUE TITLE
Documentation: Files vs wiki

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#418]
I think we should put most of our focus into using github's repo wiki instead of documentation in the docs folder.

Using the wiki allows anyone to contribute to our documentation without having to go through the PR process which can be a big hurdle for many to climb. It also encourages smaller changes which might be a hassle even for devs to PR.

**Comment by linaori** [comment]
It's an option, personally not a big fan of the wiki but it can work.

**Comment by mheguy** [comment]
What would you like to use for documentation?

**Comment by der-dave** [comment]
I like this idea. GitHub wiki is easier to use for syling the article than doing it in the docs flder.

**Comment by mheguy** [comment]
We moved to the wiki. Issue closed.
