### ISSUE TITLE
Stone particles for cave collapses

### ISSUE THREAD

**Issue by linaori** [Valansch/RedMew#423]
When digging, it would be really nice to use stone crumbling down from the ceiling to indicate where the stress levels are getting close to collapsing. When a collapse is triggered, we can spawn a bunch of particles spread over ticks to indicate where it happens, instead of the text appeared. You can play around with this command to see what the effects are:

`
/c local i = 10 while i > 0 do game.player.surface.create_entity{position=game.player.position,name='stone-particle', movement={math.random(-5, 5)*0.005, math.random(-5, 5)*0.005}, frame_speed=1, vertical_speed=0.13, height=1} i = i - 1 end
`

**Comment by linaori** [comment]
There's a create_particles.lua in the features directory where we can add new presets for this. Might have to build a small framework to do this spread over multiple ticks with tasks though.

**Comment by SimonFlapse** [comment]
Hasn't this already been implemented?

**Comment by mheguy** [comment]
Probably?
