### ISSUE TITLE
Error when using console on new server inteface

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#426]
427.329 Script @/factorio/2/temp/currently-playing/utils/event.lua:22: /factorio/2/temp/currently-playing/utils/game.lua:21: bad argument #2 to '__index' (string expected, got nil)

Arises from sending text from the server console into the game.

**Comment by Valansch** [comment]
I saw that too, not sure wahts causing it the error msg is not helpful. Needs investigating!

**Comment by mheguy** [comment]
It's coming from chat_triggers
