### ISSUE TITLE
22960.446 Script @/factorio/1/temp/currently-playing/utils/event.lua:22: .../temp/currently-playing/features/train_station_names.lua:13: attempt to get length of field 'players' (a nil value)

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#440]
**Describe the bug**
nil error in console

**Expected behavior**
No nil error in console

**Steps to reproduce**
1. Go to console
2. Look at nil error
3. See error

**Screenshots**
![grafik](https://user-images.githubusercontent.com/10226478/48924198-029b7080-eeb6-11e8-879f-5f63915ae64a.png)

**Map**
Any map

**Additional context**
22960.446 Script @/factorio/1/temp/currently-playing/utils/event.lua:22: .../temp/currently-playing/features/train_station_names.lua:13: attempt to get length of field 'players' (a nil value)

**Comment by grilledham** [comment]
change line 13 from
```lua
local x = math.random(1, #Game.players)
```
to
```lua
local x = math.random(1, #game.players)
```
