### ISSUE TITLE
Poll, poll-results, and task commands should be removed

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#450]
Nobody uses them. The poll command was broken for a few weeks before somebody noticed.

Not even @Valansch likes command-line so much that they want to list poll options in a command string. :D

I might include `tag` on this list as well, but command-line gives admins the chance to assign tags to unwilling players and that can be fun. :D

**Comment by grilledham** [comment]
the poll and poll result commnads allow you to create polls from the server console and view the result. I want to keep them

**Comment by mheguy** [comment]
fair enough for me
