### ISSUE TITLE
Change Task.lua, Queue.lua PriorityQueue.lua to conform to the naming convention of other files

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#452]
`Task`, `Queue`, and `PriorityQueue` should conform with the other utilities' naming conventions. Non-caps, underscores and not camelcase.

**Comment by grilledham** [comment]
Can we also change `global_token` to just `token`?
When I first implemented it we couldn't decide on the name which is why most code is
`Token = require 'utils.global_token'

**Comment by linaori** [comment]
A few more points: 
 - `utils.list_utils` -> `utils.table`
 - `utils.utils`, not sure what to change it to though
 - make snake_case the convention to avoid windows/linux case sensitivity errors

**Comment by mheguy** [comment]
Most of these will be addressed in #464.

Changing `Queue` to `queue` and `Task` to `task` will not be trivial as neither linux nor windows systems will automatically rename a file's casing by default.

I can think of 2 possible solutions:
* Rename the files to something intermediate (ex. tasks or task_rename) and then rename them a few weeks from now, once the intermediate name has propagated to all devs/forks.
* Rename the files to something else permanently.

Option 2 is cleaner, but requires coming up with new names.

**Comment by linaori** [comment]
Git should be able to handle this: https://stackoverflow.com/questions/1793735/change-case-of-a-file-on-windows

Haven't looked into depth, but it seems possible, one way or another.

**Comment by mheguy** [comment]
The problem is not pushing the change, it's the pull. By default git doesn't seem to change filenames when only the casing has changed.

I created a commit with an intermediate name and then another to name it back to be sure the name was changed. I pulled the commits onto the linux server that we host on, and the file names did not change.
