### ISSUE TITLE
Market Popup is empty after /c game.reload_script()

### ISSUE THREAD

**Issue by TRDragony** [Valansch/RedMew#453]
**Describe the bug**
Today I have updated my save via /c game.reload_script() (I was still collecting stone instead of XP), and while the "XP collecting mechanism" now works, the "Market" button opens an empty pop up with nothing but the close button in it.

Please tell me if I did something wrong updating the Scenario. I don't assume that I have to start a new game each time I download an update?

**Expected behavior**
/c game.reload_script() updates the save and after a save + restart the game works as expected.

**Steps to reproduce**
Use /c game.reload_script() to update your save game.

**Map**
Single Player game with newest Factorio version.

**Additional context**
Discord does not work with my browser.

**Comment by linaori** [comment]
> Please tell me if I did something wrong updating the Scenario. I don't assume that I have to start a new game each time I download an update?

In theory that's how it works. Most updates will most likely work, but bigger changes of the system will require a restart. Patching running games is a complex thing that we don't support.

The way market items are calculated is currently tightly coupled to the XP system, when using the new system, it can indeed trigger an empty market. Does getting levels grant you the market items back?

Hopefully we can reduce the frequency of this issue when we've fixed #445, but it's not a simple problem to fix.

**Comment by TRDragony** [comment]
I would not mind if I start with 0 XP. The problem is, that the whole pop up is empty. It doesnt show anything. Just the close button. On a new game it opens a big pop up with XP overview and levels to come and what they will provide.

**Comment by TRDragony** [comment]
In case of a "Sorry pal, no fix", is there maybe a way to disable the automatic bot deconstruction module without restarting the game? Because that one does not really work with mines having extended range. After some time it flags my mines for deconstruction, although they still have ore below them. I haven't filed a bug report for this one as it might only happen with the mod Mining+, which I use to make single player gaming more fun with this Scenario.

So in case I can't update my save, a work-around for me would be to disable the auto-.deconstruct module by console. I havent find a way to do it. Is there one?

**Comment by linaori** [comment]
Ah you mean _that_ market button, I thought you referred to the other one. I honestly don't know if you can fix this as I don't know how Factorio handles this. 

Are you using a modded version with different miners? Because the deconstruction system doesn't work well with modded miners. I believe there was a fix presented on Discord, but it was never turned into a PR. It can be fixed by making the auto-deconstruct use the `resource_searching_radius` instead of miner names. You can try to remove the contents of the auto-deconstruct function in your save and see if that prevents the deconstruct.

**Comment by TRDragony** [comment]
Yeah I am using the mod "Mining+" and the mines have different names, as the modder has created 2 new mines. So I got you right that there won't be a fix for it? Hmmm :(
So to disable the auto deconstructer, I have to unzip the save and comment it out? There is no console command for it?

**Comment by linaori** [comment]
That's sadly the only way to do it afaik. We're accepting a patch for it as we know what's wrong the and right fix. The thing is that it doesn't influence vanilla and thus has no priority for us to fix as we don't play it in modded scenarios. 

Another option would be to create a command to turn on or off specific features, which would be an interesting concept, but currently hard to do.

**Comment by TRDragony** [comment]
Maybe you will add all fancy stuff when it gets mature. Its a great thing! Good work!

**Comment by linaori** [comment]
@TRDragony I've created an issue in the backlog (#454) so it won't disappear from our radar.
