### ISSUE TITLE
Update the auto-deconstruct script to work with the miner radius instead of name

### ISSUE THREAD

**Issue by linaori** [Valansch/RedMew#454]
Mods being played with the autodeconstruct might have issues with miners being marked for deconstruction while they are not done yet (as reported in #453). The issue is that the script checks for the mining drill name and makes some assumptions. Mods add new prototypes that have different names with different ranges. Reference: https://github.com/Refactorio/RedMew/blob/2442d3f6b37f19f81db4d5374af600b99e8bad31/features/autodeconstruct.lua#L10-L14

Solution could be to use `resource_searching_radius` of the prototype instead, and make it possible to turn the feature off with a command.

**Comment by linaori** [comment]
Could potentially be solved in a very easy fashion by checking if the miner has a target: https://lua-api.factorio.com/latest/LuaEntity.html#LuaEntity.mining_target

**Comment by Starholme** [comment]
Appears to have been resolved during #910 and included in pull request #911 

Should we keep it open to refactor the area check with mining_target mentioned above?
