### ISSUE TITLE
Expanding stat tracking

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#472]
Opening this issue to brainstorm some ideas on what stats we might want to track on players both long (server side across maps) and short term (per map) now have the ability to track stats server-side.

Don't be shy to add or suggest silly things, it can lead to something awesome.

* Playtime
* Coins
* Distance traveled
* Deaths
* Deaths
* Entities built
* Trees chopped
* Total kills by train

**Comment by Newcott** [comment]
Items Handcrafted. 
Belts Laid.
Bots used/Killed/lost.
Used Chat.
Vehicles created.
Landfill used. 
Fog of War / Void uncovered ( area discovered).
Damage taken from enemy.
Damage dealt.
Time in pollution area.
Track assemblers specifically made by players (e.g. - If I place down the red science assemblers then can see how many red flasks I've made over a game) 
Ammo count of each ammo used. 
Average Speed over time. 
Number of items delivered by bots.
Number of items placed by bots. 
Number of each module type placed.

**Comment by SimonFlapse** [comment]
Stuff brought in the market

**Comment by mheguy** [comment]
Number of splitter priorities set 😆

**Comment by mheguy** [comment]
number of kicks/bans for admins

**Comment by mheguy** [comment]
track time since last logon, with the intent being automated removal from regulars list after extended absence. maybe with time played factored in.

**Comment by mheguy** [comment]
>Belts Laid.
Bots used/Killed/lost.
Vehicles created.
Landfill used.

Those are all available from the production and kill screens, so I don't think I'll add those.

>Fog of War / Void uncovered ( area discovered).
Track assemblers specifically made by players (e.g. - If I place down the red science assemblers then can see how many red flasks I've made over a game)
Ammo count of each ammo used.
Number of items delivered by bots.

Not trivial to implement. For ammo: The nearest approximation would be to take ammo produced, subtract ammo used for crafting, and return that number. But that wouldn't take into account non-crafted ammo such as the shop or the free ammo in crash.

>Damage taken from enemy

Can and will track health lost, but that excludes any mitigation from shields or armor.

>Time in pollution area.

Any particular reason or just a curiosity?

>Average Speed over time.

Game speed?

>Number of each module type placed.

Too similar to the number in the production charts.

>Stuff brought in the market

Possible to do, but would require a rethink of the market system since there's no 'name' attached to the boosts, and the index of the boosts can change with code revisions.

>Number of splitter priorities set

Funny to think about, but no

>number of kicks/bans for admins

Would rather not create an incentive for kicking/banning.

Everything not explicitly listed here will be included in a coming PR.

**Comment by mheguy** [comment]
Time since last logon will need some server-side bits since we can't get the system time from inside the game.

**Comment by grilledham** [comment]
I'm working on a way to get server time from a script. Should open up some possibilities.

**Comment by mheguy** [comment]
Dope. Spinning the log-tracking into its own issue since #484 should close this.

**Comment by theorangeangle** [comment]
Some statistics regarding player count would be nice:

) number of people online, counted every 15mins 
) way to compare current player counts to similar, past maps (i.e. is crash site performing better than normal, average or worse?)

That way we can extrapolate what times are the busiest and make changes based on peak activity times.

It would also be nice if there were some auto-generated graphs to go along with the data (any of it) so there isn't the hassle of plugging into a spreadsheet. Maybe down the road we can auto-share an "interesting fact" of the day on Reddit, discord or ingame.

**Comment by mheguy** [comment]
```
100k celebration - 376
100x tech cost - 454
ant farm - 152
bacon islands - 441
beach2 - 271
beach3 - 592 - 2d12h
beach - 186
world thanks giving - 354
world - 381
world b - 439
winding road - 395
void gear worms - 436
void gears - 130
vanilla - 172
triangle of death - 201
triangle of death 2 - 432
triangle of death c - 384
toxic jungle - 338
toxic_danger_ore_jungle - 447
tiny_ores_final - 207
tetris - 352 - 4d3h
square_spiral_final - 166 - 3d16h
spiral_of_spiral_final - 341 - 3d12h
prehistoric_factorio_final - 288 - 2d19h
no_roboports_final - 307 - 2d1h
maltease_crossings_final - 408 - 2d23h
lines_and_squares_final - 432 - 3d12h
lines_and_squares_2_final - 327 - 5d17h
line and trees final - 67 - 3d6h
island_resort_final - 355 - 3d5h
hub_spiral_final - 444 - 2d22h
grid_islands_rotated_final - 526 - 5d8h
grid_islands_final - 339 3d10h
fruit_loops_final - 83 - 3d18h
fruit_loops_dangerous_ores_final - 425 - 2d13h
fruit_loops_3_final - 357 - 3d10h
fractal_balls_final - 307 - 2d16h
fish_islands_final - 152 - 2d21h
fish_islands_2_final - 356 - 3d1h
factory_final - 130 - 1d13h
dna_final - 148 - 3d16h
diggy_4_final - 380 - 2d17h
diggy_3_final - 509 - 3d2h
diggy2_final - 491 - 2d10h
danger_ore_b_final - 578 - 1d15h
danger_ores_2_final - 310 - 3d14h
creation_of_adam_final - 136 - 2d7h
creation_of_adam_2_final - 204 - 2d21h
crash_site_0.3.3_d_final - 310 - 1d5h
crash_site_0.3.3_c_final - 416 - 1d16h
crash_site_0.3.2_b_final - 250 - 1d10h
crash_site_0.3.0_final - 252 - 0d20h
crash_site_0.2.1_final - 296 - 1d5h
crash_site_0.2.0_final - 96 - 3h
crash_site_0.1.0_final - 307 - 1d17h
connected_dots_final - 371 - 3d18h
circular_spiral_final - 355 - 3d18h
broken_web_final - 240 - 2d11h
```

**Comment by mheguy** [comment]
> number of people online, counted every 15mins
> way to compare current player counts to similar, past maps (i.e. is crash site performing better than normal, average or worse?)

I feel like those measurements wouldn't be meaningful in the context of factorio MP. The performance of our maps is greatly linked to what other servers are offering on a given day since players will go the most popular server. Even something like the FFF which we all thought would bring players in en masse barely registered. In fact we hit our peak player count a week *after* the FFF.

Lastly and I think most importantly: I, as a dev, want to make things that everyone finds fun. But ultimately I also want to work on what interests me. I personally don't want to feel pressured to balance my maps in a way that I don't find fun or interesting, even if it means losing potential players.

>That way we can extrapolate what times are the busiest and make changes based on peak activity times.

We don't want to measure our maps for that, our maps are only one variable in a larger machine. You want something that checks for all players in MP at a given time. Having stats to back it up would be beneficial, but I'm fairly certain the server is most active in the EU evening, 1600 - 2300 UTC.

**Comment by linaori** [comment]
> You want something that checks for all players in MP at a given time.

If combined with RedMew stats, we can see how popular our maps are

**Comment by Valansch** [comment]
https://steamcharts.com/app/427520#1m
this is what you are looking for :)

**Comment by linaori** [comment]
This shows everyone who has the game open, doesn't show those who play outside of steam nor does it show who's playing online

**Comment by Valansch** [comment]
It is a large enough data set. We can reasonably assume that the percentage of players being afk in game and in single player is fairly constant.

**Comment by Valansch** [comment]
![image](https://user-images.githubusercontent.com/10226478/49430388-2e1e3500-f7ab-11e8-9ad0-b8cff0badc7b.png)
This is GMT+1. So 11:00 GMT+0 would be the best launch time on Saturday.


![image](https://user-images.githubusercontent.com/10226478/49430591-bc92b680-f7ab-11e8-9377-02b021412529.png)
13:00 in GMT+0.
