### ISSUE TITLE
Donators have no regular permissions

### ISSUE THREAD

**Issue by der-dave** [Valansch/RedMew#503]
Descrition of bug:
---------------------
Donators are not handled the same like regulars. Donators for example cant create polls. On hovering the mouse on the "Create poll" button a message like "Sorry, you Need to be a regular to create polls." appears.
This also happens for creating tags, but in this case the button "Create tag" isnt even shown.

Expected behavior:
---------------------
Donators should be handled the same like Regulars but also with their dnator perks.

Map:
-----
All maps, ist a bug in the RedMew framework

Screenshot:
-------------
![Screenshot](https://www.der-dave.com/redmew/bug503-regular-vs-donator.png)

**Comment by mheguy** [comment]
Would:
`return Utils.cast_bool(global.regulars[player_name] or global.regulars[player_name:lower()])`
to
`return Utils.cast_bool(global.regulars[player_name] or global.regulars[player_name:lower()]) or global.Donators[player_name]` 
fix this?

Edit: in the interim I've manually added the donators that didn't have regular status (3 cases)

**Comment by Valansch** [comment]
Yes.
RedMew is officially "pay2grief" now :D

**Comment by mheguy** [comment]
Closing, as in https://github.com/Refactorio/RedMew/pull/506 it was established that each rank should be modular and not hierarchical.

Edit: In the future we will need to be more conscientious of adding donators as regulars.
