### ISSUE TITLE
Fix /help

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#512]
/help sucks. However we can simply ignore the games output and print additional lines after the game printed the /help spam.

Now that we have the command wrapper we could:
- Print one line for each custom_command (Including description)
- Maybe /help list will show the traditional /help command only
- Only show the commands that the player is allowed to execute. For example hide /promote and /regular for non admins and hide server commands for all players. Alternatively this could be color coded. instead of hidden.

**Comment by linaori** [comment]
Could keep track of the descriptions of each command. Example: `/help promote` would show the help for promote. Perhaps we could add a `help` option to the wrapper that supports multi line help messages when `/help` is used

**Comment by Valansch** [comment]
/help promote, does already show the help for promote. This is vanilla.

**Comment by mheguy** [comment]
@linaori do you feel search command covers all this? Could you expand it to cover this?

**Comment by linaori** [comment]
What would you like to see added to it?

**Comment by mheguy** [comment]
>Only show the commands that the player is allowed to execute.

(I'm not sure if search-command already does this)

**Comment by linaori** [comment]
Command search shows all of them, but can fix (with some extra introspection)
