### ISSUE TITLE
Color

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#519]
Move colors server-side and create commands for players to set their colors.

**Comment by linaori** [comment]
Sounds good! 

Perhaps a `/save-color` that picks their current?

**Comment by Valansch** [comment]
I think catching /color should work even better.

**Comment by mheguy** [comment]
I was thinking: extend `/color` to include (lots) more preset colors and a randomizer. Also creating `/color-store <set/reset>`. Set: saves your color server-side. Reset: removes your saved color.

The rationale being: people expect /color to work as-is, so we don't want to mess with that. But we can extend the spectrum a bit. Many players do not want the same color every map (https://github.com/Refactorio/RedMew/issues/195#issuecomment-410858101) so making it opt-in with the ability to later opt-out seems like the best fit.

Attaching it all to `/color` is possible, but I feel it would never be discovered naturally. Inquisitive people will type `/help` to find the command list but likely wouldn't run `/help color` since they already know what it does.

**Comment by linaori** [comment]
Perhaps a game.print or force.print to show what the player did and how to do it yourself?

**Comment by mheguy** [comment]
Closed by #566 and #668
