### ISSUE TITLE
Big rock grants no experience

### ISSUE THREAD

**Issue by gorzakos** [Valansch/RedMew#531]
Big rocks do not grant experience when mined in diggy.

**Comment by gorzakos** [comment]
it still seems to provide support, and can still get coins by mining

**Comment by mheguy** [comment]
Which version of diggy, the latest release or the dev version?

**Comment by linaori** [comment]
I've just tested this in the latest version on the develop branch and both manual and bot mining gives XP for all 3 rocks (rock-huge, rock-big, sand-rock-big)

**Comment by gorzakos** [comment]
it was the develop branch. I don't know how to correlate it with a specific release, but I'll update to the latest since it is reported to fix it.

**Comment by linaori** [comment]
@gorzakos if you experience any issues after updating, please check the factorio logs and see if there are any errors, feel free to create a new issue if it's still broken.

**Comment by gorzakos** [comment]
after getting some help updating, I can confirm that develop branch I downloaded no longer has the issue reported.

**Comment by mheguy** [comment]
Awesome, thanks for following up. 😄
