### ISSUE TITLE
Map generation artifact(s)

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#542]
**Describe the bug**
Triangle_of_death chunk not being processed as expected (not forming a triangle). Because of the behaviour in Venus (a few chunks not processing properly) I'm wondering if they're linked.

**Expected behavior**
When generating triangle_of_death I expected a triangle.

**Steps to reproduce**
1. Launch triangle of death
2. Explore SE of spawn.

**Screenshots**
https://cdn.discordapp.com/attachments/432568711698710540/522526116372545577/unknown.png
![image](https://user-images.githubusercontent.com/10162554/49901289-cc0aa300-fe2e-11e8-876a-6c4929aefa95.png)

**Map**
triangle_of_death 

**Additional context**
I compared the map generated today with https://github.com/Refactorio/RedMew/commit/1942f0cf0fb435e577e5941e2ed6c57bbe5125c9 to Triangle_of_death_c_start.zip from 2018/09/18 12:40:55. The artifact was not present in the previous save.

**Comment by grilledham** [comment]
commit e827589 fixes this

**Comment by mheguy** [comment]
Whatever the issue was, is it limited to triangle?

**Comment by grilledham** [comment]
In this case yes

**Comment by mheguy** [comment]
Coolio
