### ISSUE TITLE
Super-Rich tendrils are endless by design?

### ISSUE THREAD

**Issue by TRDragony** [Valansch/RedMew#544]
In the Diggy map I found a very rich and thick tendril of mixed ore. Is it called tendril? Its the only source of serious amounts of ore. I just wonder if those tendrils have an end somewhere? I have been following the path for several chunks already, but it seems that this one just won't come to an end. Its not really a bug report. Sorry, but Discord doesnt work here.

**Comment by Valansch** [comment]
Did you change any config values? They should end yes, but they can get rather big.

**Comment by linaori** [comment]
As far as I know, they don't stop. However, there were some changes to the default config recently, having smaller veins that are impure (80% purity or so). Do you know which tendril config you've loaded?

**Comment by TRDragony** [comment]
I did not change the config and the tendril I mean is completely impure and contains all ore-types.
I attached a screenshot so you know what I mean. This "arm" is very long already.

**Comment by TRDragony** [comment]
Attachment
![out](https://user-images.githubusercontent.com/45318865/50011593-d490e400-ffbc-11e8-8591-42712dd83bb6.jpg)

**Comment by linaori** [comment]
That indeed looks like the previous default config, new one is still "infinite" though. The new config is more like this:

![image](https://user-images.githubusercontent.com/1754678/50011662-f2f6df80-ffbc-11e8-9a85-fb09d48cffee.png)
![image](https://user-images.githubusercontent.com/1754678/50011701-04d88280-ffbd-11e8-8656-6be052dd8544.png)

**Comment by TRDragony** [comment]
Yeah I am playing an older version and for me its quite fun to only have mixed ore :)
On your screenshots they don't seem to end. So they don't have an end?

**Comment by TRDragony** [comment]
Your screenshot is very helpful. Is it possible for you to do a screenshot from a much more zoomed out view? That would be great.

**Comment by linaori** [comment]
I don't have any, sorry. These are the ones the BlueRock made when he was working on the feature
