### ISSUE TITLE
Editor config to automatically setup text editors and IDEs to use spaces over tabs

### ISSUE THREAD

**Issue by linaori** [Valansch/RedMew#547]
This can be done by adding a [`.editorconfig`](https://editorconfig.org/) file in the root of the project with the following contents. It's not invasive and supported by the majority of editors. 

```ini
# top-most EditorConfig file
root = true

# Unix-style newlines with a newline ending every file
[*]
end_of_line = lf
insert_final_newline = true

# Matches multiple files with brace expansion notation
# Set default charset
[*.lua]
charset = utf-8
indent_style = space
indent_size = 4
```

**Comment by mheguy** [comment]
Created https://github.com/Refactorio/RedMew/wiki/Dev-environment to close this.
