### ISSUE TITLE
Automatically limit passive provider chests to a configurable open slots

### ISSUE THREAD

**Issue by linaori** [Valansch/RedMew#551]
On the beach map someone suggested it would be nice if there was a mod to automatically limit the amount of open slots a passive provider chests has. Obviously a mod is overkill and we can actually do this in a scenario!

Should probably be done when an entity is placed by either a bot or player. Can use this API: https://lua-api.factorio.com/latest/LuaInventory.html#LuaInventory.hasbar

 - Might have to check whether it came from a blueprint and has pre-configured limited slots. 
 - Might cause issues with buffer stations that use passive provider chests. Fix for this is to adjust one and drag copy the rest

This can be implemented as RedMew  `features/limit_provider_chest.lua` and receive a configurable amount of slots (defaults to 1).

**Comment by mheguy** [comment]
This is essentially all that is needed to check for existing conditions and set it. 

Do need to double-check that the bar settings on an entity placed from a BP are set when the event triggers.
```lua
if #LuaEntity.get_inventory(defines.inventory.chest)+1 == LuaEntity.get_inventory(defines.inventory.chest).getbar() then
    LuaEntity.get_inventory(defines.inventory.chest).setbar(2)
end
```

**Comment by mheguy** [comment]
You think only passive providers? Or Steel + Passive provider chests?

**Comment by linaori** [comment]
In theory could also make this a player setting 🤔 That would leave the decision up to the player

**Comment by mheguy** [comment]
If we make it optional, I would vote to make it opt-out rather than opt-in.

**Comment by mheguy** [comment]
Maybe the first time they drop a restricted chest it pops up a notice letting them know.

**Comment by mheguy** [comment]
Written, PR to come after #565 is merged
