### ISSUE TITLE
Desync source

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#556]
Just on my way out the door but this came from a recent desync report.

![image](https://user-images.githubusercontent.com/10162554/50059428-acd48400-0154-11e9-85d5-920899968320.png)

**Comment by mheguy** [comment]
If I had to guess, from terraforming

**Comment by Valansch** [comment]
Did you export both saves in the same tick?

**Comment by mheguy** [comment]
Yes the same tick, I'll have a PR in the future with a tool so we can all do the same.
