### ISSUE TITLE
Notify Admins if Regulars decon more than x entities

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#57]

**Comment by theorangeangle** [comment]
I guess we're going through old issues now, so this one is a good one to bring to light as well

**Comment by Valansch** [comment]
It is already implemented, but not for regulars. Its for guests. We can change it to notifiy for regulars too. But i dont think there is much sense in that.

**Comment by theorangeangle** [comment]
Depending on how liberal we are with giving out the regular rank on maps that require it for more of the userbase than normal (ex: forest maps where lots of people need decon rights) we might run into problems where someone obtains regular through lying and then decons the whole base. Maybe we set it to an extremely high number like 25k? That way only massive decons would be registered.

**Comment by iltar** [comment]
Is this issue still something that needs some follow-up, or can we close it as won't fix?

**Comment by Valansch** [comment]
Close as won't fix :)
