### ISSUE TITLE
Finish Tetris

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#582]
Todo list:

- [x] Trees
- [x] Make the buttons behave as the market, using the sprite buttons
   - "number" on the button is the amount of votes so you can see what's going on
   - Use the "tooltip" to indicate the action
   - show voters
- [x] Show a timer on when the vote closes
- [x] Add biters
- [x] Disable buttons after vote
- [ ] Keep the tetrominoes visible at all times
- [x] Make chest unminable
- [x] Change drop to down
- [ ] (Fix wrong amounts in chest)
- [x] Fix "rotate clockwise" text
- [x] Chart new terrain more aggressively
- [ ] Rechart map if resources are destroyed
- [x] Fix resource duplication when rotating. How to reproduce: (X marks resources)
```
[ ][ ]
   [ ][X]
```

**Comment by Fudster** [comment]
Can you make the chest minable when it's empty?

**Comment by Valansch** [comment]
That was my thought too. Yes thats possible.

**Comment by Valansch** [comment]
I cannot reproduce the wrong amount in chests anymore. /shrugs

**Comment by mheguy** [comment]
Closed via #582

**Comment by Valansch** [comment]
Nonono closed via #605

**Comment by mheguy** [comment]
Lol, closed via itself. bravo me
