### ISSUE TITLE
Tasklist desync

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#585]
I've read on discord that task list causes desyncs and experienced it firsthand with silly holiday names. I set a task and as soon as I did desynced. Will investigate and expand on this. In the interim https://github.com/Refactorio/RedMew/pull/584 will temporarily disable the feature.

**Comment by mheguy** [comment]
![image](https://user-images.githubusercontent.com/10162554/50380550-93da4000-0638-11e9-97fa-e3cd5a13cb02.png)
A diff of `level.dat` from when the desyncs started on silly_names. "wall defense" was the task entered and I did it from the server console.

**Comment by linaori** [comment]
Should be fixed with #632
