### ISSUE TITLE
Rebrand silly_player_names

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#586]
There are a lot of technical hurdles to having a player's name change and having those changes carry over to the next time they log in. Mainly that if they ever exit the game in any way that doesn't trigger `on_pre_player_left_game` we lose their association to a LuaPlayer. The cause I personally experienced was having to restart the server.

So @theorangeangle came up with a great idea: don't fix it. Embrace the anarchy. In fact roll back on efforts to keep the association to a LuaPlayer. Instead, advertise that you're anonymous. Once you log off, your body is gone so you better give away all your worldly possessions (optionally, could make that automatic).

Also gives me an idea for a config options where, when you die, there is no corpse.

Usually I just list these things in my project for myself, but this one needed more text so I had to make it an issue. :D

More notes:

have name-check work backwards and forwards (silly name to actual name, actual name to silly name)

create way to specify naming scheme

**Comment by theorangeangle** [comment]
I definitely push for embracing the anarchy whenever possible - people responded well on Reddit to joining a server anonymously and got me thinking if this should be a larger feature.

Would it be possible to give the player an option to play anonymously when they join, with a button on the info menu? Of course, this would require the following:
-A list of names that isn't christmas related
-A "waiting" or "standby" state to mask all player names from when they join the map to when they exit the menu 

And this assumes it's the player responsibility to opt in to anonymity, which it should be (with the exception of themed maps like the holiday event)

**Comment by mheguy** [comment]
Link to old file: https://github.com/Refactorio/RedMew/blob/28daf88f21ae58dd871f74b68d13dbfce54e8531/map_gen/shared/silly_player_names.lua

**Comment by mheguy** [comment]
From what I've read, we can no longer change player names, so I see no reason to do anything with silly player names.
