### ISSUE TITLE
Nudge people towards more engagement

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#590]
On this latest map so far:
266 players, and of them 175 never looked at more than just the first tab of the info screen (forced on join). A further 22 looked at more than 1 but not all. And 69 looked at all 5 tabs.

Lin's thoughts via discord:
>Could probably do some sort of help messages over time :thinking:
Linaori: after 30 seconds
>- check if the player has said something
>- if not, tell them how to talk
after 60 seconds, point them to the help screen

I would increase the times by a factor of 20, but I like the idea of small nudges. One poke after 10 minutes of silence might be welcome. Similarly a last poke after 20 minutes or so of silence about the info screen seems a propos.

**Comment by grilledham** [comment]
Another way to look at those stats is that most people don't want the info screen and to just play the game. Maybe w should do the opposite and not show the info screen on player_created.

**Comment by mheguy** [comment]
I'm more than happy to experiment on our users with some AB testing. :D

Control = auto-open + small reward 

control - auto-open
control + increased reward
control + increased reward - auto-open
control but auto-open to map info
control - auto-open + message 10 mins post-join about getting info
control - auto-open + message 10 mins post-join about getting info and reward
