### ISSUE TITLE
A way to reduce nuclear explosions in diggy

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#591]
If nuclear explosions are still an issue in diggy, I propose the following fix:
```lua
local function on_entity_damaged (event)
    local entity = event.entity
    if entity and entity.name and entity.name == 'nuclear-reactor' then
        entity.temperature = entity.temperature - 101
    end
end
```
It shouldn't increase calculation time much since diggy already, if memory serves, has an on-damage function you can piggyback on.

I think this can still trigger an explosion if a player brings the reactor to the brink of death, waits for the temperature to rise back, then kills the reactor in 1 shot.

But that would require a very active effort.

If the explosions aren't an issue or this doesn't seem like something you want to add, feel free to close this issue.

**Comment by linaori** [comment]
Sounds like a good idea

**Comment by mheguy** [comment]
Given that diggy already suffers from high cpu use, hooking anything onto on_ent_dmg is probably a bad idea.

**Comment by linaori** [comment]
The CPU usage is primarily coming from scanning the surface when opening rooms and somewhat when digging, this is fairly intensive.
