### ISSUE TITLE
prison command

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#6]

**Comment by Valansch** [comment]
think about kill command

**Comment by plague006** [comment]
What would you want prison to be/look like? What's the objective of it?

**Comment by theorangeangle** [comment]
Currently walkabout serves as our "jail" command as it moves the player out into the wild and onto a separate force. 

If we wanted to accomplish a physical jail while keeping the player on the same force, we could likely generate a 7x7 wall / "box" area, place those walls on the enemy force, teleport the player into the box and move them into a permission group disabling their weapons.

**Comment by plague006** [comment]
Ok so for the most basic implementation of this, we want to:
add a command `/jail name` (restricted to admins)
if not created, create the Jail permission group and set the appropriate actions allowed (everything restricted except writing to console to allow them to speak?)
then we want to put `name` into that group

we also likely want to have 
`/unjail name` (restricted to admins)
to move `name` back to the `Default` group
