### ISSUE TITLE
Localization Support

### ISSUE THREAD

**Issue by Yukinyaa** [Valansch/RedMew#606]
I was trying to fork and translate the strings at `/locale/en`, but the localization file seems to be not the only string the scenario has.

It would be wonderful if the strings are all in `/locale/*`

Or, at least there could be rule that each `.lua` file should have string on topmost part of the file.

**Comment by mheguy** [comment]
Just wanted to give a heads up that work has started on this. It will still take a while as there are a lot of systems to refactor, but we will get there.

**Comment by Yukinyaa** [comment]
@plague006 
I am so happy to hear that 👍
Looking forward to play with translation for my folks in Korea 🏭 
Edit: I just wanted to thank you, which I forgot. Thanks for... well.... everyting :D
