### ISSUE TITLE
Factorio 0.16 crash loading RedMew_Diggy from release 1.1.0

### ISSUE THREAD

**Issue by yadij** [Valansch/RedMew#615]
**Describe the bug**
Loading the Diggy scenario on Linux immediately crashes factorio 0.16.51.

All files in the RedMew_Diggy.zip release expand from the .zip release download with 000 permissions and timestamps. This causes Factorio to be unable to open any files and crashes attempting to load the scenario.

--------- 1 test test  190 Jan  1  1980  ~/.factorio/scenarios/RedMew_Diggy/locale/en/announcements.cfg
---------- 1 test test  1383 Jan  1  1980  ~/.factorio/scenarios/RedMew_Diggy/locale/en/freeplay.cfg
---------- 1 test test  588 Jan  1  1980  ~/.factorio/scenarios/RedMew_Diggy/locale/en/score-extended.cfg

If this is intentional, then there are install instructions missing for how to update the permissions for use on Linux.

**Comment by linaori** [comment]
My guess is that the ZIP is created on windows, but that shouldn't cause any issues in Linux afaik. @plague006 made the zip I believe

Also weird that the date is `Jan 1 1980`, that can't be right

Edit: both the Diggy and Crash site seem to have this issue, the full zip is saying nov-2018

**Comment by mheguy** [comment]
Zip was created in windows using 7-Zip 18.05.
Public releases were an avenue we were experimenting with but didn't really work out. It has just taken me a little while to revert the documentation and remove the releases.

You should find instructions on installing diggy here: https://github.com/Refactorio/RedMew/wiki/Map-guide%3A-Diggy
