### ISSUE TITLE
popup not only as "Attention!" popup

### ISSUE THREAD

**Issue by der-dave** [Valansch/RedMew#636]
I would like to be able to set the popup window to not only show an attention with a warning icon.

It would be good for me to also show "Error!" or "Success!" with different icons.

**Comment by SimonFlapse** [comment]
I extracted all the icons from triangle of death:
![image](https://user-images.githubusercontent.com/44922798/51754511-c9050280-20bc-11e9-82a2-4d9213cf8f7a.png)

I'm thinking of changing the "Attention!" popup to allow for custom title, and icon based on the 13 icons shown in the image.
