### ISSUE TITLE
Styleguide: change to no trailing commas for multi-line table definitions

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#639]
I like the trailing comma, it makes sense. But the tools I, and others, use don't support formatting in that style. So I'm left either formatting by hand or using an extra tool for formatting to maintain compliance. 

To me, neither is an acceptable solution so for easier use and compliance I propose changing the style to no trailing commas.

**Comment by mheguy** [comment]
Two thumbs up is good enough for me. No more trailing commas. Change made to the wiki page.

**Comment by Valansch** [comment]
~~conspiracy successful~~ ehm i mean _great_ 👍
