### ISSUE TITLE
Implement probation rank

### ISSUE THREAD

**Issue by Valansch** [Valansch/RedMew#643]
Acts like guest rank, expect when you are on probation the following things apply:
- You will never get the decon planner, no matter how long you are in the game
- You will never get the nuke, no matter how long you are in the game
- If you are kicked by script, send a chat message to discord if possible (For the logs)
- Make /regular promote username return an error

Could be implemented together with #637

**Comment by grilledham** [comment]
Sending a chat message to the linked discord channel is as simple as `Server.to_discord(str)`

**Comment by mheguy** [comment]
Probation rank is implemented. It’s not as robust as I would like, but it covers 3/4 of the items Val listed.
