### ISSUE TITLE
Challenge Map: Purple science only obtained from biter/worm nests

### ISSUE THREAD

**Issue by theorangeangle** [Valansch/RedMew#646]
**Try to explain as best as you can what the map would look like and what the gameplay would be like.**
Disables the crafting recipe for purple science and drop purple science from biter nests and/or worm bodies upon death. Could be in conjunction with or in replacement of coin drops. 

Ideally we release it right at the time of an FFF and pretend to have "a sneak peak of 0.17 with new science recipe" for the jokes

**Comment by linaori** [comment]
Could make biter nest drop coins and make it possible to buy purple science in the market

**Comment by Jayefuu** [comment]
Since this is an idea not an issue, shouldn't it go into a section in Projects called Map Ideas?

Regarding the idea.... it sounds grindy. Additionally you'd have too much of it early game when you can't use it, and not enough late game when you do, which would frustrate players.

**Comment by SimonFlapse** [comment]
Implemented by #773
