### ISSUE TITLE
a nil value

### ISSUE THREAD

**Issue by salvomes** [Valansch/RedMew#649]
i wanted to generate my first Diggy Scenario and i got the mesaage you can see in the screenshot.

I have no idea what to do, perhaps someone else had this issue and can help
![diggy](https://user-images.githubusercontent.com/40577975/51085054-4aab7680-1734-11e9-85f1-bb373f8801c0.PNG)

**Comment by linaori** [comment]
The market has been renamed, looks like this line of code was forgotten. If you know how to change the file, change "fish_market" to "market" and it will work. I'll have a fix ready in a few minutes otherwise.

**Comment by salvomes** [comment]
oh wow, that was extreme fast. thanks a lot

**Comment by linaori** [comment]
If you download the latest version, it should work now, enjoy Diggy 😄
