### ISSUE TITLE
Voidfinity Chest

### ISSUE THREAD

**Issue by theorangeangle** [Valansch/RedMew#651]
**Is your feature request related to a problem? Please describe.**
Some people want infinity chests, while others want void chests. This is an attempt to please the best and worst of both worlds.

**Describe the solution you'd like**
A chest that, every 10 minutes, either doubles its capacity or deletes its contents.

**Describe alternatives you've considered**
Having both an infinity chest and void chest, but combining them seems more fun 😄 

**Additional context**
Probably only to be used in Dangerores.

**Comment by linaori** [comment]
What's the difference?

**Comment by Valansch** [comment]
![grafik](https://user-images.githubusercontent.com/10226478/51117070-04761600-180d-11e9-8b6e-eb547344034e.png)
