### ISSUE TITLE
Finish clearing out linting warnings

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#658]
We're in the home stretch and almost have all our linting under wraps. @Valansch wanted an issue open to keep track of this, so here it is:

- [x] Checking features/antigrief.lua                   1 warning
    features/antigrief.lua:180:23: (W422) shadowing definition of argument player on line 155
- [x] Checking features/gui/blueprint_helper.lua        2 warnings
    features/gui/blueprint_helper.lua:66:15: (W421) shadowing definition of variable ents on line 20
    features/gui/blueprint_helper.lua:123:15: (W421) shadowing definition of variable ents on line 77
- [x] Checking map_gen/Diggy/Feature/DiggyCaveCollapse.lua 3 warnings
    map_gen/Diggy/Feature/DiggyCaveCollapse.lua:404:5: (W113) accessing undefined variable mask_init
    map_gen/Diggy/Feature/DiggyCaveCollapse.lua:537:10: (W111) setting non-standard global variable mask_init
    map_gen/Diggy/Feature/DiggyCaveCollapse.lua:537:20: (W431) shadowing upvalue config on line 35
- [x] Checking map_gen/combined/borg_planet_v2.lua      1 warning
    map_gen/combined/borg_planet_v2.lua:89:8: (W561) cyclomatic complexity of function is too high (77 > 75)
- [ ] Checking map_gen/combined/dimensions.lua          1 warning
    map_gen/combined/dimensions.lua:64:10: (W111) setting non-standard global variable run_combined_module
- [x] Checking map_gen/ores/neko_crazy_ores.lua         1 warning
    map_gen/ores/neko_crazy_ores.lua:26:40: (W113) accessing undefined variable d
- [x] Checking map_gen/presets/crash_site/blueprint_extractor.lua 2 warnings
    map_gen/presets/crash_site/blueprint_extractor.lua:87:10: (W111) setting non-standard global variable extract1
    map_gen/presets/crash_site/blueprint_extractor.lua:138:10: (W111) setting non-standard global variable extract4
- [x] Checking map_gen/presets/crash_site/outpost_builder.lua 9 warnings
    map_gen/presets/crash_site/outpost_builder.lua:1:7: (W211) unused variable Random
    map_gen/presets/crash_site/outpost_builder.lua:15:7: (W211) unused variable not_level_bit_mask
    map_gen/presets/crash_site/outpost_builder.lua:19:7: (W211) unused variable section_straight
    map_gen/presets/crash_site/outpost_builder.lua:20:7: (W211) unused variable section_outer_corner
    map_gen/presets/crash_site/outpost_builder.lua:21:7: (W211) unused variable section_inner_corner
    map_gen/presets/crash_site/outpost_builder.lua:56:16: (W211) unused function get_direction
    map_gen/presets/crash_site/outpost_builder.lua:75:16: (W211) unused function set_level
    map_gen/presets/crash_site/outpost_builder.lua:80:16: (W211) unused function set_block
    map_gen/presets/crash_site/outpost_builder.lua:84:16: (W211) unused function get_block
- [x] Checking map_gen/presets/crash_site/outpost_data/big_stone_factory.lua 1 warning
    map_gen/presets/crash_site/outpost_data/big_stone_factory.lua:40:7: (W211) unused variable factory_c
- [x] Checking map_gen/shape/infinite_mazes.lua         1 warning
    map_gen/shape/infinite_mazes.lua:135:5: (W311) value assigned to variable maze_seed is unused
- [x] Checking map_gen/shape/spiral.lua                 1 warning
    map_gen/shape/spiral.lua:13:20: (W113) accessing undefined variable d
- [x] Checking map_gen/shape/spiral_tri.lua             1 warning
    map_gen/shape/spiral_tri.lua:1:23: (W212) unused argument world
- [x] Checking map_gen/terrain/neko_bridged_rivers.lua  7 warnings
    map_gen/terrain/neko_bridged_rivers.lua:2:7: (W211) unused variable simplex
    map_gen/terrain/neko_bridged_rivers.lua:6:10: (W111) setting non-standard global variable run_terrain_module
    map_gen/terrain/neko_bridged_rivers.lua:17:11: (W211) unused variable tileswater
    map_gen/terrain/neko_bridged_rivers.lua:25:17: (W113) accessing undefined variable run_ores_module
    map_gen/terrain/neko_bridged_rivers.lua:86:24: (W113) accessing undefined variable run_ores_module
    map_gen/terrain/neko_bridged_rivers.lua:87:25: (W113) accessing undefined variable run_ores_module_setup
    map_gen/terrain/neko_bridged_rivers.lua:89:29: (W113) accessing undefined variable run_ores_module_tile

**Comment by Valansch** [comment]
> Checking map_gen/combined/borg_planet_v2.lua 1 warning
map_gen/combined/borg_planet_v2.lua:89:8: (W561) cyclomatic complexity of function is too high (77 > 75)
I think the solution here is to add a lint exception ;) I don't think anyone wants to change borg planet :D

**Comment by linaori** [comment]
cyclomatic complexity should be a warning at most imo. There are legit cases where cyclomatic complexity is high, usually related to performance.

**Comment by mheguy** [comment]
> should be a warning at most imo

They're all warnings
