### ISSUE TITLE
Crash Site Features: Combat Robots as defense

### ISSUE THREAD

**Issue by theorangeangle** [Valansch/RedMew#659]
**Is your feature request related to a problem? Please describe.**
Crash site needs to be harder, late-game

**Describe the solution you'd like**
Spawn combat robots in outposts when they are attacked to make it harder for capturing. 

**Describe alternatives you've considered**
Increasing how fast evolution evolves. 

**Additional context**
Small outpost = nothing
Medium outpost = distractor (passive attacking)
Large outpost = destroyer (active attacking)

**Comment by theorangeangle** [comment]
Tacking on another feature: Combat research (gun turret damage/speed, laser damage/speed, etc) should also increase the power of the enemy force defenses.

**Comment by grilledham** [comment]
>> Tacking on another feature: Combat research (gun turret damage/speed, laser damage/speed, etc) should also increase the power of the enemy force defenses.

I don't like that idea. It doesn't make sense to me to punish the player for something that's supposed to reward them. Evolution is already the mechanic that punishes the player, and I use it to increase enemy turret damage.

Regarding the issue suggestion. I need to experiment to see how plausible the idea is. I wonder if you can make the spawned combat robots target players, or do they just idea about.

**Comment by theorangeangle** [comment]
Ah, if evolution increases enemy turret damage then that is good enough for me.

The distractor robots stay in place unless something comes into their view (so only if players try to liberate?) while destroyers actively seek targets IIRC.

**Comment by adrianvanderwal** [comment]
>while destroyers actively seek targets IIRC.

From the wiki:
>The Destroyer robots have infinite laser energy and will follow the player, attacking any enemies that come within range, until they run out of health or their lifespans elapse.

The defender bots would spawn in the outpost, and stay there until something from an enemy force comes into range.
Unless of course you could spawn them, and give them a target point, perhaps the origin, which they would then path towards, destroying whatever is in the way.

**Comment by Zahir-Khan** [comment]
#985

**Comment by theorangeangle** [comment]
#985
