### ISSUE TITLE
Looks like collapse function broken

### ISSUE THREAD

**Issue by Azzoo** [Valansch/RedMew#661]
Hi! Thanks for interest scenario!
I've tried to game today and see there no collapsing stones.
I've tested releases and looks like an error somewere between 
91e18a7a96c0710cc62ee67c18b50e555b374f43 (there is this function looks working)
3f8be3151af63d0d8de368f051a581dba719e407 (looks like collapse function broken).

Maybe there is only conflict in my Factorio ver 16.51. I've removed all other mods when testing.
Maybe this issue can help you debug event subsystem.
Thanks.

**Comment by grilledham** [comment]
I was able to fix it by changing 
```lua
on_surface_created({surface_index = 1})
```
```lua
on_surface_created({surface_index = 2})
```
here
https://github.com/Refactorio/RedMew/blob/develop/map_gen/Diggy/Feature/DiggyCaveCollapse.lua#L402

Not a great solution but it at least shows the problem area.

Also noticed this line
https://github.com/Refactorio/RedMew/blob/develop/map_gen/Diggy/Feature/DiggyCaveCollapse.lua#L406
Calls `RS.get_surface()` outside an event, which the comments say is not safe to do.

**Comment by Azzoo** [comment]
Thank! Is surface_index should be 1 ? I see 0.5 index somewhere, when collapse calculating. 
I don't know LUA as well, but is "local surface" variable working lile "closure" in JavaScript ?

**Comment by linaori** [comment]
Looks like it's tightly coupled to Nauvis at this part, while we use the RedMew surface now. @plague006 do you have a recommendation to fix this?

**Comment by grilledham** [comment]
I can think of 3 ideas of the top of my head, from what I consider best to worst
1. Refactor to use surface.name instead of surface.index `RS.get_surface_name()` is safe to call at anytime and works correctly even if redmew_surface is disabled
2. Use `on_init` and `on_load` to get the surface with `RS.get_surface()` then you can use the index for the returned surface.
3. use 
```lua
if global.config.redmew_surface.enabled then
    index = 2
else
    index = 1
end
