### ISSUE TITLE
Corpse looting alert!

### ISSUE THREAD

**Issue by MyNameIsRomayne** [Valansch/RedMew#665]
When someone dies, other players will sometimes go to collect it without other said person's consent. This means they can take any items they want without them noticing, if nobody else is near/looking on the radar. Making it even worse, a person may take a random, maybe important item and remain under the radar. This can lead the newly respawned person to be agitated, and then open a whole issue to mods and admins that might not be able to get evidence. 

        Solving this could happen in a few ways. I will list pros and cons of each idea. The higher number the method (1-etc), the more intense and violent it is.

1: Send a warning in chat (Preferred)

     When a player loots/opens a corpse of another, a message may appear in chat saying "x has looted y's corpse!" This may startle said looter and scare them off, or at least provide evidence that said person has rifled through y's corpse. This also lets people take items from a recently deceased person's corpse with their consent while still putting something in chat. However, this by no means stops them from taking the items from the corpse, and you would not know what they have inside the corpse.

2: Remove the ability for others to take the corpse without a clicked button by the deceased person

    When a player tries to mine/open a corpse, it stops them and gives the deceased person a pop-up asking if they can open their corpse. Then, said person can explain if they want to take a specific item or the whole thing. If the deceased person says no, then the looter is denied access. This would work great as well, but if said dead person left, the corpse is inaccessible until they rejoin. To fix that, though, you could just leave it lootable if the person is not on, and still have "x has looted y's corpse!" for added evidence in case the person just crashed.

Removed 3-6 because I want to be professional. Please take 1-2 into consideration. 3-6 will be posted on the discord. I hope this can solve the issue!

**Comment by mheguy** [comment]
Closed via #667
