### ISSUE TITLE
Groundhog's Day changes to burner only/Prehistoric

### ISSUE THREAD

**Issue by theorangeangle** [Valansch/RedMew#710]
I'm encouraging 3 changes to the burner only map (Prehistoric Factorio) to coincide with groundhog's day, this Saturday.

1) Add 3 new images of groundhogs to the mapgen
2) Auto-decon: Either remove so that burner miners aren't triggered early, or fix so that they are deconned only when depleted.
3) Inserters - upgrade stack size to 2 at map start

**Comment by theorangeangle** [comment]
Images: https://cdn.discordapp.com/attachments/531733389238075393/539475002689585163/groundhog1.png
https://cdn.discordapp.com/attachments/531733389238075393/539475003838824459/groundhog2.png
https://cdn.discordapp.com/attachments/531733389238075393/539475005033938953/groundhog3.png

**Comment by SimonFlapse** [comment]
Would you like to have the stack size upgraded by unlocking the technology or us setting the bonus manually? Allowing for a stack size of 4 instead of the regular 3 through research

**Comment by theorangeangle** [comment]
Probably manually, so that we start at 2 instead of 1 and subsequently
upgrade with research from there.

If we have time, maybe another max size or two upgrade that can bought with
the market?

**Comment by SimonFlapse** [comment]
Alright, I started making the map. I have a suggestion:
~~We could bind inserter stack size to the stack inserter research.~~
Edit: Should have looked at the map code before saying that, it's already how it works

**Comment by SimonFlapse** [comment]
That's one of them. Not the best quality, but I'd rather not spend all day manipulating the images to make it better.
![image](https://user-images.githubusercontent.com/44922798/52144191-e2c6bc80-265d-11e9-997e-1914a5cebd62.png)

**Comment by SimonFlapse** [comment]
After about 40 failed seed attempts I accepted this map:
![image](https://user-images.githubusercontent.com/44922798/52145620-ccbafb00-2661-11e9-829a-cd735a0f41be.png)
I might tweak the ores, but otherwise it's my result

**Comment by SimonFlapse** [comment]
Closing since map has launched
