### ISSUE TITLE
Toast instructions on how to chat for new players 

### ISSUE THREAD

**Issue by theorangeangle** [Valansch/RedMew#736]
If a player has not said anything in chat for 5 minutes (exact time TBD) and is not a regular, they are given a toast with instructions on how to send messages in chat.

**Comment by theorangeangle** [comment]
Could be absorbed into #590 .

**Comment by theorangeangle** [comment]
After #762 we can toast individual players - maybe after five minutes if the player has not said something in chat one of the following messages is sent out?

If the player has moved (either at all, or at least a measurable amount): 

> Hello there, and welcome to RedMew! We're glad you have walked around a bit, and wanted to make sure you knew about the ingame chat feature. 
To chat with other players, press the "grave" key on your keyboard. 
(It is below the ESC key on English keyboards and looks like ~ or ` , and can be changed in options -> controls -> "toggle lua console"). 

If the player has not moved:

> Welcome to RedMew! If you haven't already, feel free to take a walk around with your character, or a look around with the minimap (M key). Specific map information can be found in the ? mark button, located above this message (along with rules, links and descriptions about what those other buttons do). Speaking of messages, don't hesitate to say hello in the chat!
To chat with other players, press the "grave" key on your keyboard. 
(It is below the ESC key on English keyboards and looks like ~ or ` , and can be changed in options -> controls -> "toggle lua console").

**Comment by mheguy** [comment]
For clarity, #762 only added a command for admins to use the toast functions. Toast was always able to send per-player toasts.
