### ISSUE TITLE
When we use destroy, revive, or create_entity, see if passing `raise_event` to the function is appropriate

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#739]
In 0.17 the above-mentioned functions will be able to take arguments to raise the custom events themselves. See: https://lua-api.factorio.com/0.17.0-preview/events.html#script_raised_built

It will at least be worth investigating what data is passed through the table.

**Comment by Bilka2** [comment]
You get `entity` and the usual things that any event contains (`tick` and `name`), as documented.
