### ISSUE TITLE
Config doesn't finish loading before required map modules require redmew_surface

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#751]
Loading an entity_module via the config will cause the scenario to fail to load:

```
...Data/Roaming/Factorio/temp/currently-playing/control.lua:14:
 ...pData/Roaming/Factorio/temp/currently-playing/config.lua:27:
 ...p/currently-playing/map_gen/entities/fluffy_rainbows.lua:5:
 ...temp/currently-playing/map_gen/shared/redmew_surface.lua:66:
attempt to index field 'config' (a nil value)
```

**Comment by mheguy** [comment]
Issue may be in other modules, but in fluffy_rainbows it's because it wants to call for the seed of the play surface. I could revert the change and have it call surface[1] directly, but this means we can't control the seed of the module from `redmew_surface`.

**Comment by grilledham** [comment]
Loading anything in config that uses the config is going to be problematic.
Without dynamic requires, the only solution that comes to mind is to set `entity_modules` to a function that is then called to return the table, i.e.
```lua
['entity_modules'] = function()
return
 {
    -- require('map_gen.entities.fluffy_rainbows'
 }
end,
```

**Comment by mheguy** [comment]
Got around this by wrapping the required in a function (grilled's idea ofc because he loves to wrap everything in functions). #781
