### ISSUE TITLE
[Diggy] Late game issues

### ISSUE THREAD

**Issue by SimonFlapse** [Valansch/RedMew#771]
Bot based mining from personal roboports causes massive ups drop when inventory size if > 1000

I'd propose taking a look at the very late game diggy experience system.

- Remove inventory bonus entirely OR limit it to eg. 100
- Tweak experience requirements for level up in, since one research gives 70+ levels at level 20k

**Comment by linaori** [comment]
Now that mining rocks no longer gives out stone/coal, I propose we remove the buffs completely, same goes for HP buffs.

**Comment by SimonFlapse** [comment]
We added health instead of the stone sent to surface buff because of hail hydra. But we could remove it or limit it so that players doesn't have 60k health

**Comment by Spy426-IW16** [comment]
Figured i would throw out a thought. Is there anyway to add these buffs to the market with a scaling coin cost? I was wondering as an additional issue with the later game is that there are currently a lot of coins doing nothing. Thought was to have people buy the extra slot of inventory and after purchase have the cost double or something for the next and if possible set a limit that it can only be purchased X times. Maybe limit to 25. Do a similar thing with the health buff possibly.

**Comment by linaori** [comment]
> Is there anyway to add these buffs to the market with a scaling coin cost?

There is, but it's per force and not per player. Currently it _is_ possible to limit the amount of purchases per player though. In the current state that means you have to add the buff multiple times at different prices. 

In theory it's possible to calculate the price based on items remaining and make this dynamic _per player_, but this would require a dynamic formula system and I'm not sure how to implement this. Perhaps @grilledham has input on this
