### ISSUE TITLE
regular remove <player> doesn't remove/change server data

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#779]
... and it makes them auto-trusted instead of guest if playtime < required

**Comment by grilledham** [comment]
While we are add it, I really think we should change the regular command to `/regular` for promote and `/regular-demote` for demotes

**Comment by mheguy** [comment]
I can begrudgingly agree with splitting it into 2 commands. But I strongly urge us to stay away from the words `promote` and `demote` because of how many times I've seen admins use `/promote` on a player.

**Comment by grilledham** [comment]
OK, `/regular-remove` work for you?

**Comment by mheguy** [comment]
Yep

**Comment by mheguy** [comment]
You tell the troops this time though, I've changed it on them enough. :p
