### ISSUE TITLE
Sorting by rank in the player list only works for sort descending

### ISSUE THREAD

**Issue by Jayefuu** [Valansch/RedMew#792]
If you press the player list and sort by rank, it only shows players when sorting by descending. If you sort ascending all players disappear.

**Comment by Jayefuu** [comment]
![image](https://user-images.githubusercontent.com/28716932/53263490-76296580-36d1-11e9-9fd4-935113883812.png)

**Comment by grilledham** [comment]
For me

![image](https://user-images.githubusercontent.com/10003572/53263599-cd2f3a80-36d1-11e9-8029-4b9afb0b9996.png)

![image](https://user-images.githubusercontent.com/10003572/53263611-d3251b80-36d1-11e9-90ef-2fe5e169a644.png)

**Comment by grilledham** [comment]
There are errors in the logs though
`features/gui/player_list.lua:550: invalid order function for sorting`

**Comment by Jayefuu** [comment]
I think it's related to your command I ran then

**Comment by mheguy** [comment]
Resolved. This was related to a scenario data issue.
