### ISSUE TITLE
Customizable tag messages

### ISSUE THREAD

**Issue by Quadrum1** [Valansch/RedMew#800]
**Is your feature request related to a problem? Please describe the problem.**
I'm always frustrated when you create a tag and the "verb" does not really fit into the pre-generated message

**Describe the solution you'd like**
Introducing: Fully customizable join/leave messages

Giving players 2 text fields to write a customizable join and leave tag message.

{tagname} and {playername} should be filled out by the script and shown as a tooltip when creating the tag.  

**Describe alternatives you've considered**
Some form options to choose from.
eg.
1. [tag] squard {verb} with {playername}
2. {playername} {verb} {tag}
3.  etc.

**Additional context**
To tackle the input of {tag} and {player}, this code should work:

`joinMessage = "{tagname} squad put {playername} into their ranks"`
`squad = "Trooper"`
`player = "Quadrum"`

`output = string.gsub(joinMessage,"{tagname}",squad) `
`output = string.gsub(output,"{playername}", player)`
`print(output)`

Output: `Trooper squad put Quadrum into their ranks`

Needs to be edited for factorio api, but normal lua works already

**Comment by SimonFlapse** [comment]
I'd say we should wait until we will have a look at the GUI after 0.17 has been released.

**Comment by Quadrum1** [comment]
I already created a prototype out of `features\gui\tag_group.lua`. 
Although its not working without bugs (Can't clear the tag for whatever reason), the purpose is fullfilled. 

Could add the feature and just change it for 0.17 later

**Comment by SimonFlapse** [comment]
You're welcome to submit a PR. That would be a great help
