### ISSUE TITLE
Make autodeconstruct better/smarter

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#803]
We can use `entity.prototype.mining_drill_radius` to make ourselves compatible with mods. We can use `fluidbox`'s connections to see if it's transmitting sulfuric acid (or other mining fluids in modded)

**Comment by theorangeangle** [comment]
Can we fix whatever caused burner drills to be deconned early, while we're at it? I'm not sure of the exact steps to reproduce but on the first dino islands burner miners would be auto-deconned with ore still underneath them (and autodecon disabled on the second run)

**Comment by grilledham** [comment]
#911 fixed this
