### ISSUE TITLE
[17] diggy_cave_collapse: changes to on_built_tile

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#815]
In 0.17 `on_player_built_tile` the return of an item is no longer certain.

https://github.com/Refactorio/RedMew/blob/76871eefbfb5a69b2f7e32eb64a1aad25f1967e7/map_gen/maps/diggy/feature/diggy_cave_collapse.lua#L218

**Comment by adrianvanderwal** [comment]
It seems item was never used in the first place?

The parameters used in the Event have stayed the same.

```lua
Event.add(
        defines.events.on_player_built_tile,
        function(event)
            on_built_tile(game.surfaces[event.surface_index], event.item, event.tiles)
        end
    )
```
https://lua-api.factorio.com/latest/events.html#on_player_built_tile

**Comment by mheguy** [comment]
I think you're misunderstanding what I'm saying.
In the API:
```
on_player_built_tile

Called after a player builds tiles. 
Contains
player_index :: uint
surface_index :: uint: The surface the tile(s) were built on.
tiles :: array of OldTileAndPosition: The position data.
item :: LuaItemPrototype (optional): The item type used to build the tiles
stack :: LuaItemStack (optional): The stack used to build the tiles (may be empty if all of the items where used to build the tiles).
```
`item` is an optional return. Which means we should catch the case of `event.item` being `nil`.

**Comment by grilledham** [comment]
Do we know when `event.item` is `nil` is it to accommodate mods that might allow building tiles without an item in hand? Or does it happen when you place the last item in the stack?

**Comment by mheguy** [comment]
We don't know. I can try summoning @Bilka2 :)

**Comment by Bilka2** [comment]
Item is nil when using the tile editor (editor controller) to place tiles. It's also nil when the editor controller instant-builds blueprints (and that contains a tile).
