### ISSUE TITLE
List of broken shit in 0.17

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#821]
- [x] Walkabout #826 

- [x] Info gui #831 

- [x] Poll gui (create poll)

- [x] All maps that use `RS` to set single types of ground tiles ("grass", "dirt", "sand", "desert" are no longer autoplace_control_names)  #827

- [x] Terraforming uses `acid-projectile-purple` which is gone

- [x] Rotten apples lists and relies on techs that are deprecated #828

- [x] Tetris not getting a waterworld (https://forums.factorio.com/viewtopic.php?f=28&t=65371&p=401110)

**Comment by Bilka2** [comment]
You can make a waterworld with `/c game.create_surface("my-surface", {  property_expression_names = {elevation = -10}}) game.player.teleport({0,0}, "my-surface")`, see #927
