### ISSUE TITLE
Added/removed prototypes in 0.17

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#825]
Codebase checked for all removed prototypes

#### Removed (checked)
grass, dirt, sand, desert

#### Added
lichen

#### Added
compilatron-chest
escape-pod-assembler
escape-pod-lab
escape-pod-power
heat-interface
infinity-pipe
medium-spitter-corpse
behemoth-worm-corpse
assembler-wreck
lab-wreck
mineable-wreckage
compilatron
behemoth-worm-turret
acid-splash-fire-spitter-behemoth
acid-splash-fire-spitter-big
acid-splash-fire-spitter-medium
acid-splash-fire-spitter-small
acid-splash-fire-worm-behemoth
acid-splash-fire-worm-big
acid-splash-fire-worm-medium
acid-splash-fire-worm-small
acid-sticker-behemoth
acid-sticker-big
acid-sticker-medium
acid-sticker-small
acid-stream-spitter-behemoth
acid-stream-spitter-big
acid-stream-spitter-medium
acid-stream-spitter-small
acid-stream-worm-behemoth
acid-stream-worm-big
acid-stream-worm-medium
acid-stream-worm-small
compi-speech-bubble
highlight-box
laser-beam
shallow-water-droplet-particle
bait-chest
wreck-pole

#### Removed (checked)
acid-projectile-purple
acid-splash-purple
small-cliff

#### Added
signal-check
signal-dot
signal-info

#### Added
water-mud
water-shallow

#### Added

    'fast-inserter',
    'basic-optics',
    'lubricant',
    'active-defense',
    'analyse-ship',
    'basic-electronics',
    'basic-logistics',
    'basic-mapping',
    'basic-military',
    'basic-mining',
    'chemical-science-pack',
    'demo-logistics',
    'demo-science-pack',
    'electric-inserter',
    'electric-mining',
    'improved-equipment',
    'logistic-science-pack',
    'military-science-pack',
    'passive-defense',
    'production-science-pack',
    'repair-tech',
    'space-science-pack',
    'utility-science-pack',
    'steel-axe',
    'character-logistic-trash-slots-3',
    'character-logistic-trash-slots-4',
    'character-logistic-trash-slots-5',
    'demo-productivity-1',
    'demo-shooting-speed-1',
    'energy-weapons-damage-1',
    'refined-flammables-1',
    'stronger-explosives-1',
    'weapon-shooting-speed-1',
    'physical-projectile-damage-1'
    'energy-weapons-damage-2',
    'physical-projectile-damage-2',
    'refined-flammables-2',
    'stronger-explosives-2',
    'weapon-shooting-speed-2',
    'energy-weapons-damage-3',
    'physical-projectile-damage-3',
    'refined-flammables-3',
    'stronger-explosives-3',
    'weapon-shooting-speed-3',
    'energy-weapons-damage-4',
    'physical-projectile-damage-4',
    'refined-flammables-4',
    'stronger-explosives-4',
    'weapon-shooting-speed-4',
    'energy-weapons-damage-5',
    'physical-projectile-damage-5',
    'refined-flammables-5',
    'stronger-explosives-5',
    'weapon-shooting-speed-5',
    'energy-weapons-damage-6',
    'energy-weapons-damage-7',
    'physical-projectile-damage-6',
    'physical-projectile-damage-7',
    'refined-flammables-6',
    'refined-flammables-7',
    'stronger-explosives-6',
    'stronger-explosives-7',
    'weapon-shooting-speed-6',
    'uranium-processing',
    'belt-immunity-equipment',
    'low-density-structure',
    'rocket-control-unit',
    'rocket-fuel',

#### Removed (checked)

    'flying',
    'rocket-damage-*',
    'rocket-speed-*',
    'cannon-shell-damage-*',
    'cannon-shell-speed-*',
    'bullet-damage-*',
    'bullet-speed-*',
    'grenade-damage-*',
    'laser-turret-damage-*',
    'shotgun-shell-damage-*',
    'shotgun-shell-speed-*',
    'flamethrower-damage-*',
    'combat-robot-damage-*',

#### Added

    'automation-science-pack',
    'logistic-science-pack',
    'chemical-science-pack',
    'belt-immunity-equipment',
    'utility-science-pack',

#### Removed (checked)

    'iron-axe',
    'steel-axe',
    'science-pack-1',
    'high-tech-science-pack',
    'science-pack-2',
    'science-pack-3',
    'wood',

#### Added

    'compilatron-chest',
    'dummy-steel-axe', (errors if you try to insert it)
    'upgrade-planner',
    'copy-paste-tool',
    'cut-paste-tool',
    'escape-pod-power',
    'heat-interface',
    'escape-pod-assembler',
    'escape-pod-lab',
    'pollution', (calling dibs on using this for something. :D )
    'automation-science-pack',
    'logistic-science-pack',
    'chemical-science-pack',
    'utility-science-pack',
    'selection-tool',

#### Removed (checked)
    'iron-axe',
    'dummy-selection-tool',
    'steel-axe',
    'science-pack-1',
    'science-pack-2',
    'science-pack-3',
    'high-tech-science-pack',

**Comment by SimonFlapse** [comment]
Many thanks 🥇

**Comment by mheguy** [comment]
Moved everything into https://github.com/Refactorio/RedMew/wiki/0.17-New-features-and-prototypes-to-tinker-with
