### ISSUE TITLE
Error in hail_hydra

### ISSUE THREAD

**Issue by mheguy** [Valansch/RedMew#878]
(Server time: 2019-03-02 05:12:36)
Time of error: 9 hours 35 minutes
RedMew version: Time of map launch: 2019-03-01 19:33:13 UTC
Target must be entity with force.
stack traceback:
	...o/3/temp/currently-playing/map_gen/shared/hail_hydra.lua:147: in function <...o/3/temp/currently-playing/map_gen/shared/hail_hydra.lua:73>
	[C]: in function 'pcall'
	/factorio/3/temp/currently-playing/utils/event_core.lua:32: in function 'call_handlers'
	/factorio/3/temp/currently-playing/utils/event_core.lua:43: in function </factorio/3/temp/currently-playing/utils/event_core.lua:41>

**Comment by grilledham** [comment]
I don't see any mention of this in the logs for the diggy server, so I'm going to assume this was fixed.
