### ISSUE TITLE
Nest translations instead of appending them as parameters

### ISSUE THREAD

**Issue by linaori** [Valansch/RedMew#941]
With this setup we can nest translations (this code is buggy, just an example) instead of appending them, which would hit the 20 parameter limit. See #940 and #879 
```lua
-- untested
function append_locale(what, add_this)
    if not what[3] then
        what[3] = add_this
        return what
    end

    return append_locale(what, what[3])
end
```

**Comment by grilledham** [comment]
This was solved by #944, #945 and #948 unless there are still more modules that need changing?
