### ISSUE TITLE
Feature request: changelog

### ISSUE THREAD

**Issue by AndrewTru** [Valansch/RedMew#966]
but is there a way to see what's added or removed in a update/patch.
it's hard to keep a save going unless I know it's not going to brake or if it will.

I understand this is a date page of all the ones you all make but just a small page or file that says thanks for updating here's what's new thing.
A change log if you will.

**Comment by theorangeangle** [comment]
We keep a log of major scenario changes on the version history tab of our wiki, at https://github.com/Refactorio/RedMew/wiki/Version-History. This is also sometimes displayed ingame.


However, typically a Factorio version update (from 0.17.49 to 0.17.50) will not break the scenario - the easiest way to check is by going in discord and asking for the server version. If the maps are updated a couple hours after the latest experimental drops, it means we had no issues with updating (and neither should you 😁)

**Comment by AndrewTru** [comment]
thanks for the tip, just checking the in-game display is not saving I think.
It's the same message every time I checked.

**Comment by theorangeangle** [comment]
I’m pretty sure that if you create the scenario locally it might not come with our list of recent changes, which is synced on our backend to our hosted servers. 

However, we can try to work on a way of keeping the recent changes in all downloaded scenarios.

**Comment by mheguy** [comment]
If you’re updating the scenario code inside an existing save, we cannot ensure that the scenario will not break. It would really be best if you completed a full playthrough with a single version of the scenario.

We experimented with a changelog in the scenario in the past, but ultimately the effort required to keep it up to date was a significant challenge.
