### ISSUE TITLE
Crash Site Laser Turret Infinite Range

### ISSUE THREAD

**Issue by cshotton** [Valansch/RedMew#969]
**Describe the bug**
On vanilla install of latest Factorio beta from Steam, current Crash Site, laser turrets have standard range for engaging player, but have infinite range when trying to disengage. Once locked on, they fire across the full width of the map if you can last that long and run that far.

**Expected behavior**
Turrets should stop firing when player moves out of the usual laser turret range.

**Steps to reproduce**
Generate a new crash site map, walk up to a laser turret, try to run away.

**Screenshots**
see attached
<img width="583" alt="laser" src="https://user-images.githubusercontent.com/490077/61724178-6f178980-ad3b-11e9-9b7c-d095775ba5c2.png">

**Map**
see above. vanilla single player crash site on vanilla beta app

**Additional context**

**Comment by grilledham** [comment]
I'm pretty sure that is a vanilla factoiro bug. If it's not fixed in the next release I'll make a bug report.

**Comment by grilledham** [comment]
0.17.59 fixed this
