### ISSUE TITLE
Turret Autofill Toggle in config.lua has no effect.

### ISSUE THREAD

**Issue by Soggs** [Valansch/RedMew#975]
Well this 
`
-- autofill turrets with ammo    
    autofill = {
        enabled = false
    },
`
does nothing. Case and point the Ribbons and Recursion run on s8.

To recreate simply make new scenario with autofill off and give yourself some turrets via the editor.

**Comment by grilledham** [comment]
I thought I fixed this, but I guess not. 
Changing `if config.autofill then` to `if config.autofill.enabled then` in control.lua should fix it

**Comment by theorangeangle** [comment]
A fix has been applied in #976
