### ISSUE TITLE
Map Idea - Escape Earth

### ISSUE THREAD

**Issue by HySpeed** [Valansch/RedMew#977]
# Map Idea: Escape Earth

## Concept

This scenario combines these elements:
* **Game Map of Earth**: Factorio World / World Map scenarios
* **Outposts & resource**: Crash Site scenario
* **Market purchases & upgrades**: Crash Site scenario
* **Static Rocket Silo location**: Frontier scenario

## Player Description
You have returned to Earth and find it overrun with aliens.  The goal is to escape Earth, but the technology to build a rocket silo has been lost.  A Rocket Silo is located in South America -- the landing site is in Africa.  To get to the silo, the aliens have to be battled and a path forged across the world.  Surface resources are gone.  Resources are produced by mines that must be captured and powered.  
[optional]
The scans before landing showed a possible alternate rocket silo on a remote island in the South Pacific - getting resources to that location will be difficult because of limited throughput. 

### Earth Map
The Earth map used by the Factorio World scenario is scalable.  Using this technology, a world map can be created, modified in the editor, then exported for use as a static map.  The optimal size is unknown (noted below in 'Tricky Parts').  Also, see below about Land Fill.
* In the map editor, a land bridge must be created between northeast Russia and Alaska (Arctic circle).  This bridge will be wide enough for train lines and power connections. (e.g. minimum 6 tiles).
* In the map editor, Central America / Panama must be wide enough for train and power connections also.
* If the 'alternate rocket silo' is included, a narrow land bridge must be created in the editor which allows only a single belt and power connection to reach Australia.
  * The concept of the alternate silo is that players could use this, but because it is only a single belt, it should take longer to build and launch a rocket from that silo.  The benefit is that the players do not have to conquer the American continent.

## Outposts
The outposts of Crash Site will be used to provide basic resources only (e.g. no assembled items) - (coal, stone, iron ore, copper ore, uranium ore, oil, water, etc)
(If water is provided through an outpost, the offshore pump could be removed.  The benefit is neglibable, but the concept of tweaking another feature of the game is worth considering.)
* Initial outposts - those within the base - would be limited to level 1 and not upgradable.  If possible, they could be less than level 1.  

## Map Layout Ideas
* MLI1: The starting base is the middle of Africa - South Africa is a 'dead end', but would serve well for additional resource outposts that would get the player going in the early-to-mid game.  Their upgradability should be limited (e.g. level 4).
* MLI2: There should be value in some of the 'out of the way' areas of the map (Europe, Eastern Canada, etc.).  The player's basic movement will be northeast from Africa to Russia, then down to South America.  Limiting some resources or defining high-content resources in these other areas will help guide the players to explore & conquer the map.
* MLI3: The 'choke points' should represent difficult challenges with extra defenses:
  * Northeast Africa
  * Northeast Russia
  * Northwest Canada
  * Central America

## Technology Changes
* The Land Fill technology is disabled so that the player cannot bypass the challenge of the map by building a 'land bridge'
* The Rocket Silo technology is disabled so that the player must find and secure the rocket silo

## Additional / Optional Features
* Teleportion from Cities of Earth mod

### Teleportation
If it is possible, a menu item could be added to some of the outpost markets that allows a player to teleport to a different outpost market.  The cost would vary based on the distance between the current outpost and the selected outpost (via drop-down).  An outpost would only be available if it is captured and powered.  The CoE mod has technology for teleport locations on a map.  The hard work will be to make it available in the markets.

## Special Work to Do
* Because the map is static and the challenge is for the player(s) to work towards the rocket silo, the world map requires custom editing to create a path large enough for trains to cross using the Arctic circle between Russia and Alaska.
* With Landfill disabled, care needs to be taken to ensure large land elements can be reached (e.g. Greenland, Australia).
* ?

## Tricky Parts
* What size map will provide a challenging and rewarding experience?
* How to use World Map as a static terrain, yet have outposts created via Crash Site code?
* Where & what resources to place on the map for a balanced progression?

## Disclaimer
* I created the Cities of Earth mod

## A Personal Note
I am willing & able to work on (or help with) this scenario.  I have studied the RedMew code and understand the basic components.  (I have not been able to figure out how to use a static map with the Crash Site outposts, but I haven't worked at it much.)  If someone from RedMew is willing to spend some time on Discord teaching me how to get started, I'm willing.  Or, if someone within RedMew wants to create a basic skeleton for me to work with, I'm game.  Also, if this gets created with no more input from me, I'll be happy just playing it! :)

## Contact
* jonTucich_at_gmail.com

**Comment by theorangeangle** [comment]
Thanks for bringing us this really detailed and fleshed out idea! I have added this to our internal roadmap.

**Comment by HySpeed** [comment]
Hi,

I have more details in my head and I'm happy to share.
If you want to talk more about it, I have some evening and weekend hours free.
I live in the US, Eastern Time Zone (GST-4/5).

thanks,
jon

**Comment by HySpeed** [comment]
Hey! I tried out the new CrashSite on Earth and it looks great!
I'm very happy you were able to make that happen.
I think that was the hardest part.

Are you planning on doing more of the features from above?

**Comment by Jayefuu** [comment]
@HySpeed Rather than allowing players to make land bridges with landfill, we could place buildings that when near players can use the /warp command to teleport between two buildings. We have a similar implementation on Space Race.

**Comment by HySpeed** [comment]
> @HySpeed Rather than allowing players to make land bridges with landfill, we could place buildings that when near players can use the /warp command to teleport between two buildings. We have a similar implementation on Space Race.

@Jayefuu Rather than a "/warp" command, an idea is to add it as something that can be purchased at a market.  The price would be determined by the distance.
