### ISSUE TITLE
Recently pushed changes stop crash site walls spawning

### ISSUE THREAD

**Issue by Jayefuu** [Valansch/RedMew#999]
As in title. No walls in crash site. 

Restart doesn't fix. Bugged in both normal and desert versions.

I loaded a version of the scenario from last week and it works fine. Had to disable /restart so that it doesn't revert on next restart.

See this file for example:
https://redmew.com/admin/servers?handler=file&serverId=7&directory=global_saves&name=bugged_wall_crash_site.zip

**Comment by grilledham** [comment]
#1000 fixed this
